// Auto-generated by codegen/bridge_codegen.py — DO NOT EDIT
// Source: vk.xml (Venus protocol standard)
#pragma once

#include "vn_stream.h"

struct VnDecode_vkBindBufferMemory {
    uint64_t device;
    uint64_t buffer;
    uint64_t memory;
    uint64_t memoryOffset;
};

static inline void vn_decode_vkBindBufferMemory(VnStreamReader* r, VnDecode_vkBindBufferMemory* args)
{
    args->device = r->readU64();
    args->buffer = r->readU64();
    args->memory = r->readU64();
    args->memoryOffset = r->readU64();
}

struct VnDecode_vkBindImageMemory {
    uint64_t device;
    uint64_t image;
    uint64_t memory;
    uint64_t memoryOffset;
};

static inline void vn_decode_vkBindImageMemory(VnStreamReader* r, VnDecode_vkBindImageMemory* args)
{
    args->device = r->readU64();
    args->image = r->readU64();
    args->memory = r->readU64();
    args->memoryOffset = r->readU64();
}

struct VnDecode_vkCmdBindIndexBuffer {
    uint64_t commandBuffer;
    uint64_t buffer;
    uint64_t offset;
    uint32_t indexType;
};

static inline void vn_decode_vkCmdBindIndexBuffer(VnStreamReader* r, VnDecode_vkCmdBindIndexBuffer* args)
{
    args->commandBuffer = r->readU64();
    args->buffer = r->readU64();
    args->offset = r->readU64();
    args->indexType = r->readU32();
}

struct VnDecode_vkCmdBindPipeline {
    uint64_t commandBuffer;
    uint32_t pipelineBindPoint;
    uint64_t pipeline;
};

static inline void vn_decode_vkCmdBindPipeline(VnStreamReader* r, VnDecode_vkCmdBindPipeline* args)
{
    args->commandBuffer = r->readU64();
    args->pipelineBindPoint = r->readU32();
    args->pipeline = r->readU64();
}

struct VnDecode_vkCmdDraw {
    uint64_t commandBuffer;
    uint32_t vertexCount;
    uint32_t instanceCount;
    uint32_t firstVertex;
    uint32_t firstInstance;
};

static inline void vn_decode_vkCmdDraw(VnStreamReader* r, VnDecode_vkCmdDraw* args)
{
    args->commandBuffer = r->readU64();
    args->vertexCount = r->readU32();
    args->instanceCount = r->readU32();
    args->firstVertex = r->readU32();
    args->firstInstance = r->readU32();
}

struct VnDecode_vkCmdDrawIndexed {
    uint64_t commandBuffer;
    uint32_t indexCount;
    uint32_t instanceCount;
    uint32_t firstIndex;
    uint32_t vertexOffset;
    uint32_t firstInstance;
};

static inline void vn_decode_vkCmdDrawIndexed(VnStreamReader* r, VnDecode_vkCmdDrawIndexed* args)
{
    args->commandBuffer = r->readU64();
    args->indexCount = r->readU32();
    args->instanceCount = r->readU32();
    args->firstIndex = r->readU32();
    args->vertexOffset = r->readU32();
    args->firstInstance = r->readU32();
}

struct VnDecode_vkCmdEndRenderPass {
    uint64_t commandBuffer;
};

static inline void vn_decode_vkCmdEndRenderPass(VnStreamReader* r, VnDecode_vkCmdEndRenderPass* args)
{
    args->commandBuffer = r->readU64();
}

struct VnDecode_vkCmdEndRendering {
    uint64_t commandBuffer;
};

static inline void vn_decode_vkCmdEndRendering(VnStreamReader* r, VnDecode_vkCmdEndRendering* args)
{
    args->commandBuffer = r->readU64();
}

struct VnDecode_vkCmdSetCullMode {
    uint64_t commandBuffer;
    uint32_t cullMode;
};

static inline void vn_decode_vkCmdSetCullMode(VnStreamReader* r, VnDecode_vkCmdSetCullMode* args)
{
    args->commandBuffer = r->readU64();
    args->cullMode = r->readU32();
}

struct VnDecode_vkCmdSetFrontFace {
    uint64_t commandBuffer;
    uint32_t frontFace;
};

static inline void vn_decode_vkCmdSetFrontFace(VnStreamReader* r, VnDecode_vkCmdSetFrontFace* args)
{
    args->commandBuffer = r->readU64();
    args->frontFace = r->readU32();
}

struct VnDecode_vkEndCommandBuffer {
    uint64_t commandBuffer;
};

static inline void vn_decode_vkEndCommandBuffer(VnStreamReader* r, VnDecode_vkEndCommandBuffer* args)
{
    args->commandBuffer = r->readU64();
}
