// Auto-generated by codegen/bridge_codegen.py — DO NOT EDIT
// Source: vk.xml (Venus protocol standard)
#pragma once

#include "vn_stream.h"

static inline void vn_encode_vkBindBufferMemory(VnStreamWriter* w
    , uint64_t device
    , uint64_t buffer
    , uint64_t memory
    , uint64_t memoryOffset
)
{
    w->writeU64(device);
    w->writeU64(buffer);
    w->writeU64(memory);
    w->writeU64(memoryOffset);
}

static inline void vn_encode_vkBindImageMemory(VnStreamWriter* w
    , uint64_t device
    , uint64_t image
    , uint64_t memory
    , uint64_t memoryOffset
)
{
    w->writeU64(device);
    w->writeU64(image);
    w->writeU64(memory);
    w->writeU64(memoryOffset);
}

static inline void vn_encode_vkCmdBindIndexBuffer(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint64_t buffer
    , uint64_t offset
    , uint32_t indexType
)
{
    w->writeU64(commandBuffer);
    w->writeU64(buffer);
    w->writeU64(offset);
    w->writeU32(indexType);
}

static inline void vn_encode_vkCmdBindPipeline(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t pipelineBindPoint
    , uint64_t pipeline
)
{
    w->writeU64(commandBuffer);
    w->writeU32(pipelineBindPoint);
    w->writeU64(pipeline);
}

static inline void vn_encode_vkCmdDraw(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t vertexCount
    , uint32_t instanceCount
    , uint32_t firstVertex
    , uint32_t firstInstance
)
{
    w->writeU64(commandBuffer);
    w->writeU32(vertexCount);
    w->writeU32(instanceCount);
    w->writeU32(firstVertex);
    w->writeU32(firstInstance);
}

static inline void vn_encode_vkCmdDrawIndexed(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t indexCount
    , uint32_t instanceCount
    , uint32_t firstIndex
    , uint32_t vertexOffset
    , uint32_t firstInstance
)
{
    w->writeU64(commandBuffer);
    w->writeU32(indexCount);
    w->writeU32(instanceCount);
    w->writeU32(firstIndex);
    w->writeU32(vertexOffset);
    w->writeU32(firstInstance);
}

static inline void vn_encode_vkCmdEndRenderPass(VnStreamWriter* w
    , uint64_t commandBuffer
)
{
    w->writeU64(commandBuffer);
}

static inline void vn_encode_vkCmdEndRendering(VnStreamWriter* w
    , uint64_t commandBuffer
)
{
    w->writeU64(commandBuffer);
}

static inline void vn_encode_vkCmdSetCullMode(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t cullMode
)
{
    w->writeU64(commandBuffer);
    w->writeU32(cullMode);
}

static inline void vn_encode_vkCmdSetFrontFace(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t frontFace
)
{
    w->writeU64(commandBuffer);
    w->writeU32(frontFace);
}

static inline void vn_encode_vkEndCommandBuffer(VnStreamWriter* w
    , uint64_t commandBuffer
)
{
    w->writeU64(commandBuffer);
}

// ── Not yet generated (complex parameter types) ──
// TODO: vkAllocateCommandBuffers — complex params, needs manual or extended codegen
// TODO: vkAllocateDescriptorSets — complex params, needs manual or extended codegen
// TODO: vkAllocateMemory — complex params, needs manual or extended codegen
// TODO: vkBeginCommandBuffer — complex params, needs manual or extended codegen
// TODO: vkCmdBeginRenderPass — complex params, needs manual or extended codegen
// TODO: vkCmdBeginRendering — complex params, needs manual or extended codegen
// TODO: vkCmdBindDescriptorSets — complex params, needs manual or extended codegen
// TODO: vkCmdBindVertexBuffers — complex params, needs manual or extended codegen
// TODO: vkCmdBindVertexBuffers2 — complex params, needs manual or extended codegen
// TODO: vkCmdClearAttachments — complex params, needs manual or extended codegen
// TODO: vkCmdClearColorImage — complex params, needs manual or extended codegen
// TODO: vkCmdCopyBuffer — complex params, needs manual or extended codegen
// TODO: vkCmdCopyBufferToImage — complex params, needs manual or extended codegen
// TODO: vkCmdPipelineBarrier — complex params, needs manual or extended codegen
// TODO: vkCmdPushConstants — complex params, needs manual or extended codegen
// TODO: vkCmdSetScissor — complex params, needs manual or extended codegen
// TODO: vkCmdSetViewport — complex params, needs manual or extended codegen
// TODO: vkCmdUpdateBuffer — complex params, needs manual or extended codegen
// TODO: vkCreateBuffer — complex params, needs manual or extended codegen
// TODO: vkCreateCommandPool — complex params, needs manual or extended codegen
// TODO: vkCreateDescriptorPool — complex params, needs manual or extended codegen
// TODO: vkCreateDescriptorSetLayout — complex params, needs manual or extended codegen
// TODO: vkCreateFence — complex params, needs manual or extended codegen
// TODO: vkCreateFramebuffer — complex params, needs manual or extended codegen
// TODO: vkCreateGraphicsPipelines — complex params, needs manual or extended codegen
// TODO: vkCreateImage — complex params, needs manual or extended codegen
// TODO: vkCreateImageView — complex params, needs manual or extended codegen
// TODO: vkCreatePipelineLayout — complex params, needs manual or extended codegen
// TODO: vkCreateRenderPass — complex params, needs manual or extended codegen
// TODO: vkCreateSampler — complex params, needs manual or extended codegen
// TODO: vkCreateSemaphore — complex params, needs manual or extended codegen
// TODO: vkCreateShaderModule — complex params, needs manual or extended codegen
// TODO: vkDestroyBuffer — complex params, needs manual or extended codegen
// TODO: vkDestroyCommandPool — complex params, needs manual or extended codegen
// TODO: vkDestroyDescriptorPool — complex params, needs manual or extended codegen
// TODO: vkDestroyDescriptorSetLayout — complex params, needs manual or extended codegen
// TODO: vkDestroyFence — complex params, needs manual or extended codegen
// TODO: vkDestroyFramebuffer — complex params, needs manual or extended codegen
// TODO: vkDestroyImage — complex params, needs manual or extended codegen
// TODO: vkDestroyImageView — complex params, needs manual or extended codegen
// TODO: vkDestroyPipeline — complex params, needs manual or extended codegen
// TODO: vkDestroyPipelineLayout — complex params, needs manual or extended codegen
// TODO: vkDestroyRenderPass — complex params, needs manual or extended codegen
// TODO: vkDestroySampler — complex params, needs manual or extended codegen
// TODO: vkDestroySemaphore — complex params, needs manual or extended codegen
// TODO: vkDestroyShaderModule — complex params, needs manual or extended codegen
// TODO: vkFreeMemory — complex params, needs manual or extended codegen
// TODO: vkQueueSubmit — complex params, needs manual or extended codegen
// TODO: vkResetFences — complex params, needs manual or extended codegen
// TODO: vkUpdateDescriptorSets — complex params, needs manual or extended codegen
// TODO: vkWaitForFences — complex params, needs manual or extended codegen
