// Auto-generated by codegen/bridge_codegen.py — DO NOT EDIT
// Source: vk.xml (Venus protocol standard)
#pragma once

#include "vn_stream.h"
#include <vector>

struct VnDecode_vkAllocateMemory {
    uint64_t device;
    uint64_t pMemory;
    uint64_t pAllocateInfo_allocationSize;
    uint32_t pAllocateInfo_memoryTypeIndex;
};

static inline void vn_decode_vkAllocateMemory(VnStreamReader* r, VnDecode_vkAllocateMemory* args)
{
    args->device = r->readU64();
    args->pMemory = r->readU64();
    args->pAllocateInfo_allocationSize = r->readU64();
    args->pAllocateInfo_memoryTypeIndex = r->readU32();
}

struct VnDecode_vkBeginCommandBuffer {
    uint64_t commandBuffer;
    uint32_t pBeginInfo_flags;
};

static inline void vn_decode_vkBeginCommandBuffer(VnStreamReader* r, VnDecode_vkBeginCommandBuffer* args)
{
    args->commandBuffer = r->readU64();
    args->pBeginInfo_flags = r->readU32();
}

struct VnDecode_vkBindBufferMemory {
    uint64_t device;
    uint64_t buffer;
    uint64_t memory;
    uint64_t memoryOffset;
};

static inline void vn_decode_vkBindBufferMemory(VnStreamReader* r, VnDecode_vkBindBufferMemory* args)
{
    args->device = r->readU64();
    args->buffer = r->readU64();
    args->memory = r->readU64();
    args->memoryOffset = r->readU64();
}

struct VnDecode_vkBindImageMemory {
    uint64_t device;
    uint64_t image;
    uint64_t memory;
    uint64_t memoryOffset;
};

static inline void vn_decode_vkBindImageMemory(VnStreamReader* r, VnDecode_vkBindImageMemory* args)
{
    args->device = r->readU64();
    args->image = r->readU64();
    args->memory = r->readU64();
    args->memoryOffset = r->readU64();
}

struct VnDecode_vkCmdBindDescriptorSets {
    uint64_t commandBuffer;
    uint64_t layout;
    uint32_t pipelineBindPoint;
    uint32_t firstSet;
    uint32_t descriptorSetCount;
    std::vector<uint64_t> pDescriptorSets;
    uint32_t dynamicOffsetCount;
    std::vector<uint32_t> pDynamicOffsets;
};

static inline void vn_decode_vkCmdBindDescriptorSets(VnStreamReader* r, VnDecode_vkCmdBindDescriptorSets* args)
{
    args->commandBuffer = r->readU64();
    args->layout = r->readU64();
    args->pipelineBindPoint = r->readU32();
    args->firstSet = r->readU32();
    args->descriptorSetCount = r->readU32();
    args->pDescriptorSets.resize(args->descriptorSetCount);
    for (uint32_t i = 0; i < args->descriptorSetCount; i++)
        args->pDescriptorSets[i] = r->readU64();
    args->dynamicOffsetCount = r->readU32();
    args->pDynamicOffsets.resize(args->dynamicOffsetCount);
    for (uint32_t i = 0; i < args->dynamicOffsetCount; i++)
        args->pDynamicOffsets[i] = r->readU32();
}

struct VnDecode_vkCmdBindIndexBuffer {
    uint64_t commandBuffer;
    uint64_t buffer;
    uint64_t offset;
    uint32_t indexType;
};

static inline void vn_decode_vkCmdBindIndexBuffer(VnStreamReader* r, VnDecode_vkCmdBindIndexBuffer* args)
{
    args->commandBuffer = r->readU64();
    args->buffer = r->readU64();
    args->offset = r->readU64();
    args->indexType = r->readU32();
}

struct VnDecode_vkCmdBindPipeline {
    uint64_t commandBuffer;
    uint64_t pipeline;
    uint32_t pipelineBindPoint;
};

static inline void vn_decode_vkCmdBindPipeline(VnStreamReader* r, VnDecode_vkCmdBindPipeline* args)
{
    args->commandBuffer = r->readU64();
    args->pipeline = r->readU64();
    args->pipelineBindPoint = r->readU32();
}

struct VnDecode_vkCmdBindVertexBuffers {
    uint64_t commandBuffer;
    uint32_t firstBinding;
    uint32_t bindingCount;
    std::vector<uint64_t> pBuffers;
    std::vector<uint64_t> pOffsets;
};

static inline void vn_decode_vkCmdBindVertexBuffers(VnStreamReader* r, VnDecode_vkCmdBindVertexBuffers* args)
{
    args->commandBuffer = r->readU64();
    args->firstBinding = r->readU32();
    args->bindingCount = r->readU32();
    args->pBuffers.resize(args->bindingCount);
    for (uint32_t i = 0; i < args->bindingCount; i++)
        args->pBuffers[i] = r->readU64();
    args->pOffsets.resize(args->bindingCount);
    for (uint32_t i = 0; i < args->bindingCount; i++)
        args->pOffsets[i] = r->readU64();
}

struct VnDecode_vkCmdBindVertexBuffers2 {
    uint64_t commandBuffer;
    uint32_t firstBinding;
    uint32_t bindingCount;
    std::vector<uint64_t> pBuffers;
    std::vector<uint64_t> pOffsets;
    std::vector<uint64_t> pSizes;
    std::vector<uint64_t> pStrides;
};

static inline void vn_decode_vkCmdBindVertexBuffers2(VnStreamReader* r, VnDecode_vkCmdBindVertexBuffers2* args)
{
    args->commandBuffer = r->readU64();
    args->firstBinding = r->readU32();
    args->bindingCount = r->readU32();
    args->pBuffers.resize(args->bindingCount);
    for (uint32_t i = 0; i < args->bindingCount; i++)
        args->pBuffers[i] = r->readU64();
    args->pOffsets.resize(args->bindingCount);
    for (uint32_t i = 0; i < args->bindingCount; i++)
        args->pOffsets[i] = r->readU64();
    args->pSizes.resize(args->bindingCount);
    for (uint32_t i = 0; i < args->bindingCount; i++)
        args->pSizes[i] = r->readU64();
    args->pStrides.resize(args->bindingCount);
    for (uint32_t i = 0; i < args->bindingCount; i++)
        args->pStrides[i] = r->readU64();
}

struct VnDecode_vkCmdCopyBuffer {
    uint64_t commandBuffer;
    uint64_t srcBuffer;
    uint64_t dstBuffer;
    uint32_t regionCount;
    uint32_t regionCount;
    std::vector<uint64_t> pRegions_srcOffset;
    std::vector<uint64_t> pRegions_dstOffset;
    std::vector<uint64_t> pRegions_size;
};

static inline void vn_decode_vkCmdCopyBuffer(VnStreamReader* r, VnDecode_vkCmdCopyBuffer* args)
{
    args->commandBuffer = r->readU64();
    args->srcBuffer = r->readU64();
    args->dstBuffer = r->readU64();
    args->regionCount = r->readU32();
    args->regionCount = r->readU32();
    args->pRegions_srcOffset.resize(args->regionCount);
    args->pRegions_dstOffset.resize(args->regionCount);
    args->pRegions_size.resize(args->regionCount);
    for (uint32_t _i = 0; _i < args->regionCount; _i++) {
        args->pRegions_srcOffset[_i] = r->readU64();
        args->pRegions_dstOffset[_i] = r->readU64();
        args->pRegions_size[_i] = r->readU64();
    }
}

struct VnDecode_vkCmdCopyBufferToImage {
    uint64_t commandBuffer;
    uint64_t srcBuffer;
    uint64_t dstImage;
    uint32_t dstImageLayout;
    uint32_t regionCount;
    uint32_t regionCount;
    std::vector<uint64_t> pRegions_bufferOffset;
    std::vector<uint32_t> pRegions_bufferRowLength;
    std::vector<uint32_t> pRegions_bufferImageHeight;
    std::vector<uint32_t> pRegions_imageSubresource_aspectMask;
    std::vector<uint32_t> pRegions_imageSubresource_mipLevel;
    std::vector<uint32_t> pRegions_imageSubresource_baseArrayLayer;
    std::vector<uint32_t> pRegions_imageSubresource_layerCount;
    std::vector<int32_t> pRegions_imageOffset_x;
    std::vector<int32_t> pRegions_imageOffset_y;
    std::vector<int32_t> pRegions_imageOffset_z;
    std::vector<uint32_t> pRegions_imageExtent_width;
    std::vector<uint32_t> pRegions_imageExtent_height;
    std::vector<uint32_t> pRegions_imageExtent_depth;
};

static inline void vn_decode_vkCmdCopyBufferToImage(VnStreamReader* r, VnDecode_vkCmdCopyBufferToImage* args)
{
    args->commandBuffer = r->readU64();
    args->srcBuffer = r->readU64();
    args->dstImage = r->readU64();
    args->dstImageLayout = r->readU32();
    args->regionCount = r->readU32();
    args->regionCount = r->readU32();
    args->pRegions_bufferOffset.resize(args->regionCount);
    args->pRegions_bufferRowLength.resize(args->regionCount);
    args->pRegions_bufferImageHeight.resize(args->regionCount);
    args->pRegions_imageSubresource_aspectMask.resize(args->regionCount);
    args->pRegions_imageSubresource_mipLevel.resize(args->regionCount);
    args->pRegions_imageSubresource_baseArrayLayer.resize(args->regionCount);
    args->pRegions_imageSubresource_layerCount.resize(args->regionCount);
    args->pRegions_imageOffset_x.resize(args->regionCount);
    args->pRegions_imageOffset_y.resize(args->regionCount);
    args->pRegions_imageOffset_z.resize(args->regionCount);
    args->pRegions_imageExtent_width.resize(args->regionCount);
    args->pRegions_imageExtent_height.resize(args->regionCount);
    args->pRegions_imageExtent_depth.resize(args->regionCount);
    for (uint32_t _i = 0; _i < args->regionCount; _i++) {
        args->pRegions_bufferOffset[_i] = r->readU64();
        args->pRegions_bufferRowLength[_i] = r->readU32();
        args->pRegions_bufferImageHeight[_i] = r->readU32();
        args->pRegions_imageSubresource_aspectMask[_i] = r->readU32();
        args->pRegions_imageSubresource_mipLevel[_i] = r->readU32();
        args->pRegions_imageSubresource_baseArrayLayer[_i] = r->readU32();
        args->pRegions_imageSubresource_layerCount[_i] = r->readU32();
        args->pRegions_imageOffset_x[_i] = r->readI32();
        args->pRegions_imageOffset_y[_i] = r->readI32();
        args->pRegions_imageOffset_z[_i] = r->readI32();
        args->pRegions_imageExtent_width[_i] = r->readU32();
        args->pRegions_imageExtent_height[_i] = r->readU32();
        args->pRegions_imageExtent_depth[_i] = r->readU32();
    }
}

struct VnDecode_vkCmdDraw {
    uint64_t commandBuffer;
    uint32_t vertexCount;
    uint32_t instanceCount;
    uint32_t firstVertex;
    uint32_t firstInstance;
};

static inline void vn_decode_vkCmdDraw(VnStreamReader* r, VnDecode_vkCmdDraw* args)
{
    args->commandBuffer = r->readU64();
    args->vertexCount = r->readU32();
    args->instanceCount = r->readU32();
    args->firstVertex = r->readU32();
    args->firstInstance = r->readU32();
}

struct VnDecode_vkCmdDrawIndexed {
    uint64_t commandBuffer;
    uint32_t indexCount;
    uint32_t instanceCount;
    uint32_t firstIndex;
    int32_t vertexOffset;
    uint32_t firstInstance;
};

static inline void vn_decode_vkCmdDrawIndexed(VnStreamReader* r, VnDecode_vkCmdDrawIndexed* args)
{
    args->commandBuffer = r->readU64();
    args->indexCount = r->readU32();
    args->instanceCount = r->readU32();
    args->firstIndex = r->readU32();
    args->vertexOffset = r->readI32();
    args->firstInstance = r->readU32();
}

struct VnDecode_vkCmdEndRenderPass {
    uint64_t commandBuffer;
};

static inline void vn_decode_vkCmdEndRenderPass(VnStreamReader* r, VnDecode_vkCmdEndRenderPass* args)
{
    args->commandBuffer = r->readU64();
}

struct VnDecode_vkCmdEndRendering {
    uint64_t commandBuffer;
};

static inline void vn_decode_vkCmdEndRendering(VnStreamReader* r, VnDecode_vkCmdEndRendering* args)
{
    args->commandBuffer = r->readU64();
}

struct VnDecode_vkCmdPipelineBarrier {
    uint64_t commandBuffer;
    uint32_t srcStageMask;
    uint32_t dstStageMask;
    uint32_t dependencyFlags;
    uint32_t memoryBarrierCount;
    uint32_t memoryBarrierCount;
    std::vector<uint32_t> pMemoryBarriers_srcAccessMask;
    std::vector<uint32_t> pMemoryBarriers_dstAccessMask;
    uint32_t bufferMemoryBarrierCount;
    uint32_t bufferMemoryBarrierCount;
    std::vector<uint32_t> pBufferMemoryBarriers_srcAccessMask;
    std::vector<uint32_t> pBufferMemoryBarriers_dstAccessMask;
    std::vector<uint32_t> pBufferMemoryBarriers_srcQueueFamilyIndex;
    std::vector<uint32_t> pBufferMemoryBarriers_dstQueueFamilyIndex;
    std::vector<uint64_t> pBufferMemoryBarriers_buffer;
    std::vector<uint64_t> pBufferMemoryBarriers_offset;
    std::vector<uint64_t> pBufferMemoryBarriers_size;
    uint32_t imageMemoryBarrierCount;
    uint32_t imageMemoryBarrierCount;
    std::vector<uint32_t> pImageMemoryBarriers_srcAccessMask;
    std::vector<uint32_t> pImageMemoryBarriers_dstAccessMask;
    std::vector<uint32_t> pImageMemoryBarriers_oldLayout;
    std::vector<uint32_t> pImageMemoryBarriers_newLayout;
    std::vector<uint32_t> pImageMemoryBarriers_srcQueueFamilyIndex;
    std::vector<uint32_t> pImageMemoryBarriers_dstQueueFamilyIndex;
    std::vector<uint64_t> pImageMemoryBarriers_image;
    std::vector<uint32_t> pImageMemoryBarriers_subresourceRange_aspectMask;
    std::vector<uint32_t> pImageMemoryBarriers_subresourceRange_baseMipLevel;
    std::vector<uint32_t> pImageMemoryBarriers_subresourceRange_levelCount;
    std::vector<uint32_t> pImageMemoryBarriers_subresourceRange_baseArrayLayer;
    std::vector<uint32_t> pImageMemoryBarriers_subresourceRange_layerCount;
};

static inline void vn_decode_vkCmdPipelineBarrier(VnStreamReader* r, VnDecode_vkCmdPipelineBarrier* args)
{
    args->commandBuffer = r->readU64();
    args->srcStageMask = r->readU32();
    args->dstStageMask = r->readU32();
    args->dependencyFlags = r->readU32();
    args->memoryBarrierCount = r->readU32();
    args->memoryBarrierCount = r->readU32();
    args->pMemoryBarriers_srcAccessMask.resize(args->memoryBarrierCount);
    args->pMemoryBarriers_dstAccessMask.resize(args->memoryBarrierCount);
    for (uint32_t _i = 0; _i < args->memoryBarrierCount; _i++) {
        args->pMemoryBarriers_srcAccessMask[_i] = r->readU32();
        args->pMemoryBarriers_dstAccessMask[_i] = r->readU32();
    }
    args->bufferMemoryBarrierCount = r->readU32();
    args->bufferMemoryBarrierCount = r->readU32();
    args->pBufferMemoryBarriers_srcAccessMask.resize(args->bufferMemoryBarrierCount);
    args->pBufferMemoryBarriers_dstAccessMask.resize(args->bufferMemoryBarrierCount);
    args->pBufferMemoryBarriers_srcQueueFamilyIndex.resize(args->bufferMemoryBarrierCount);
    args->pBufferMemoryBarriers_dstQueueFamilyIndex.resize(args->bufferMemoryBarrierCount);
    args->pBufferMemoryBarriers_buffer.resize(args->bufferMemoryBarrierCount);
    args->pBufferMemoryBarriers_offset.resize(args->bufferMemoryBarrierCount);
    args->pBufferMemoryBarriers_size.resize(args->bufferMemoryBarrierCount);
    for (uint32_t _i = 0; _i < args->bufferMemoryBarrierCount; _i++) {
        args->pBufferMemoryBarriers_srcAccessMask[_i] = r->readU32();
        args->pBufferMemoryBarriers_dstAccessMask[_i] = r->readU32();
        args->pBufferMemoryBarriers_srcQueueFamilyIndex[_i] = r->readU32();
        args->pBufferMemoryBarriers_dstQueueFamilyIndex[_i] = r->readU32();
        args->pBufferMemoryBarriers_buffer[_i] = r->readU64();
        args->pBufferMemoryBarriers_offset[_i] = r->readU64();
        args->pBufferMemoryBarriers_size[_i] = r->readU64();
    }
    args->imageMemoryBarrierCount = r->readU32();
    args->imageMemoryBarrierCount = r->readU32();
    args->pImageMemoryBarriers_srcAccessMask.resize(args->imageMemoryBarrierCount);
    args->pImageMemoryBarriers_dstAccessMask.resize(args->imageMemoryBarrierCount);
    args->pImageMemoryBarriers_oldLayout.resize(args->imageMemoryBarrierCount);
    args->pImageMemoryBarriers_newLayout.resize(args->imageMemoryBarrierCount);
    args->pImageMemoryBarriers_srcQueueFamilyIndex.resize(args->imageMemoryBarrierCount);
    args->pImageMemoryBarriers_dstQueueFamilyIndex.resize(args->imageMemoryBarrierCount);
    args->pImageMemoryBarriers_image.resize(args->imageMemoryBarrierCount);
    args->pImageMemoryBarriers_subresourceRange_aspectMask.resize(args->imageMemoryBarrierCount);
    args->pImageMemoryBarriers_subresourceRange_baseMipLevel.resize(args->imageMemoryBarrierCount);
    args->pImageMemoryBarriers_subresourceRange_levelCount.resize(args->imageMemoryBarrierCount);
    args->pImageMemoryBarriers_subresourceRange_baseArrayLayer.resize(args->imageMemoryBarrierCount);
    args->pImageMemoryBarriers_subresourceRange_layerCount.resize(args->imageMemoryBarrierCount);
    for (uint32_t _i = 0; _i < args->imageMemoryBarrierCount; _i++) {
        args->pImageMemoryBarriers_srcAccessMask[_i] = r->readU32();
        args->pImageMemoryBarriers_dstAccessMask[_i] = r->readU32();
        args->pImageMemoryBarriers_oldLayout[_i] = r->readU32();
        args->pImageMemoryBarriers_newLayout[_i] = r->readU32();
        args->pImageMemoryBarriers_srcQueueFamilyIndex[_i] = r->readU32();
        args->pImageMemoryBarriers_dstQueueFamilyIndex[_i] = r->readU32();
        args->pImageMemoryBarriers_image[_i] = r->readU64();
        args->pImageMemoryBarriers_subresourceRange_aspectMask[_i] = r->readU32();
        args->pImageMemoryBarriers_subresourceRange_baseMipLevel[_i] = r->readU32();
        args->pImageMemoryBarriers_subresourceRange_levelCount[_i] = r->readU32();
        args->pImageMemoryBarriers_subresourceRange_baseArrayLayer[_i] = r->readU32();
        args->pImageMemoryBarriers_subresourceRange_layerCount[_i] = r->readU32();
    }
}

struct VnDecode_vkCmdPushConstants {
    uint64_t commandBuffer;
    uint64_t layout;
    uint32_t stageFlags;
    uint32_t offset;
    uint32_t size;
    std::vector<uint8_t> pValues;
};

static inline void vn_decode_vkCmdPushConstants(VnStreamReader* r, VnDecode_vkCmdPushConstants* args)
{
    args->commandBuffer = r->readU64();
    args->layout = r->readU64();
    args->stageFlags = r->readU32();
    args->offset = r->readU32();
    args->size = r->readU32();
    args->pValues.resize(args->size);
    r->readBytes(args->pValues.data(), args->size);
}

struct VnDecode_vkCmdSetCullMode {
    uint64_t commandBuffer;
    uint32_t cullMode;
};

static inline void vn_decode_vkCmdSetCullMode(VnStreamReader* r, VnDecode_vkCmdSetCullMode* args)
{
    args->commandBuffer = r->readU64();
    args->cullMode = r->readU32();
}

struct VnDecode_vkCmdSetDepthBiasEnable {
    uint64_t commandBuffer;
    uint32_t depthBiasEnable;
};

static inline void vn_decode_vkCmdSetDepthBiasEnable(VnStreamReader* r, VnDecode_vkCmdSetDepthBiasEnable* args)
{
    args->commandBuffer = r->readU64();
    args->depthBiasEnable = r->readU32();
}

struct VnDecode_vkCmdSetDepthBoundsTestEnable {
    uint64_t commandBuffer;
    uint32_t depthBoundsTestEnable;
};

static inline void vn_decode_vkCmdSetDepthBoundsTestEnable(VnStreamReader* r, VnDecode_vkCmdSetDepthBoundsTestEnable* args)
{
    args->commandBuffer = r->readU64();
    args->depthBoundsTestEnable = r->readU32();
}

struct VnDecode_vkCmdSetDepthCompareOp {
    uint64_t commandBuffer;
    uint32_t depthCompareOp;
};

static inline void vn_decode_vkCmdSetDepthCompareOp(VnStreamReader* r, VnDecode_vkCmdSetDepthCompareOp* args)
{
    args->commandBuffer = r->readU64();
    args->depthCompareOp = r->readU32();
}

struct VnDecode_vkCmdSetDepthTestEnable {
    uint64_t commandBuffer;
    uint32_t depthTestEnable;
};

static inline void vn_decode_vkCmdSetDepthTestEnable(VnStreamReader* r, VnDecode_vkCmdSetDepthTestEnable* args)
{
    args->commandBuffer = r->readU64();
    args->depthTestEnable = r->readU32();
}

struct VnDecode_vkCmdSetDepthWriteEnable {
    uint64_t commandBuffer;
    uint32_t depthWriteEnable;
};

static inline void vn_decode_vkCmdSetDepthWriteEnable(VnStreamReader* r, VnDecode_vkCmdSetDepthWriteEnable* args)
{
    args->commandBuffer = r->readU64();
    args->depthWriteEnable = r->readU32();
}

struct VnDecode_vkCmdSetFrontFace {
    uint64_t commandBuffer;
    uint32_t frontFace;
};

static inline void vn_decode_vkCmdSetFrontFace(VnStreamReader* r, VnDecode_vkCmdSetFrontFace* args)
{
    args->commandBuffer = r->readU64();
    args->frontFace = r->readU32();
}

struct VnDecode_vkCmdSetScissor {
    uint64_t commandBuffer;
    uint32_t firstScissor;
    uint32_t scissorCount;
    uint32_t scissorCount;
    std::vector<int32_t> pScissors_offset_x;
    std::vector<int32_t> pScissors_offset_y;
    std::vector<uint32_t> pScissors_extent_width;
    std::vector<uint32_t> pScissors_extent_height;
};

static inline void vn_decode_vkCmdSetScissor(VnStreamReader* r, VnDecode_vkCmdSetScissor* args)
{
    args->commandBuffer = r->readU64();
    args->firstScissor = r->readU32();
    args->scissorCount = r->readU32();
    args->scissorCount = r->readU32();
    args->pScissors_offset_x.resize(args->scissorCount);
    args->pScissors_offset_y.resize(args->scissorCount);
    args->pScissors_extent_width.resize(args->scissorCount);
    args->pScissors_extent_height.resize(args->scissorCount);
    for (uint32_t _i = 0; _i < args->scissorCount; _i++) {
        args->pScissors_offset_x[_i] = r->readI32();
        args->pScissors_offset_y[_i] = r->readI32();
        args->pScissors_extent_width[_i] = r->readU32();
        args->pScissors_extent_height[_i] = r->readU32();
    }
}

struct VnDecode_vkCmdSetViewport {
    uint64_t commandBuffer;
    uint32_t firstViewport;
    uint32_t viewportCount;
    uint32_t viewportCount;
    std::vector<float> pViewports_x;
    std::vector<float> pViewports_y;
    std::vector<float> pViewports_width;
    std::vector<float> pViewports_height;
    std::vector<float> pViewports_minDepth;
    std::vector<float> pViewports_maxDepth;
};

static inline void vn_decode_vkCmdSetViewport(VnStreamReader* r, VnDecode_vkCmdSetViewport* args)
{
    args->commandBuffer = r->readU64();
    args->firstViewport = r->readU32();
    args->viewportCount = r->readU32();
    args->viewportCount = r->readU32();
    args->pViewports_x.resize(args->viewportCount);
    args->pViewports_y.resize(args->viewportCount);
    args->pViewports_width.resize(args->viewportCount);
    args->pViewports_height.resize(args->viewportCount);
    args->pViewports_minDepth.resize(args->viewportCount);
    args->pViewports_maxDepth.resize(args->viewportCount);
    for (uint32_t _i = 0; _i < args->viewportCount; _i++) {
        args->pViewports_x[_i] = r->readF32();
        args->pViewports_y[_i] = r->readF32();
        args->pViewports_width[_i] = r->readF32();
        args->pViewports_height[_i] = r->readF32();
        args->pViewports_minDepth[_i] = r->readF32();
        args->pViewports_maxDepth[_i] = r->readF32();
    }
}

struct VnDecode_vkCmdUpdateBuffer {
    uint64_t commandBuffer;
    uint64_t dstBuffer;
    uint64_t dstOffset;
    uint64_t dataSize;
    std::vector<uint8_t> pData;
};

static inline void vn_decode_vkCmdUpdateBuffer(VnStreamReader* r, VnDecode_vkCmdUpdateBuffer* args)
{
    args->commandBuffer = r->readU64();
    args->dstBuffer = r->readU64();
    args->dstOffset = r->readU64();
    args->dataSize = r->readU64();
    args->pData.resize(args->dataSize);
    r->readBytes(args->pData.data(), args->dataSize);
}

struct VnDecode_vkCreateBuffer {
    uint64_t device;
    uint64_t pBuffer;
    uint32_t pCreateInfo_flags;
    uint64_t pCreateInfo_size;
    uint32_t pCreateInfo_usage;
    uint32_t pCreateInfo_sharingMode;
    uint32_t pCreateInfo_queueFamilyIndexCount;
    std::vector<uint32_t> pCreateInfo_pQueueFamilyIndices;
};

static inline void vn_decode_vkCreateBuffer(VnStreamReader* r, VnDecode_vkCreateBuffer* args)
{
    args->device = r->readU64();
    args->pBuffer = r->readU64();
    args->pCreateInfo_flags = r->readU32();
    args->pCreateInfo_size = r->readU64();
    args->pCreateInfo_usage = r->readU32();
    args->pCreateInfo_sharingMode = r->readU32();
    args->pCreateInfo_queueFamilyIndexCount = r->readU32();
    args->pCreateInfo_pQueueFamilyIndices.resize(args->pCreateInfo_queueFamilyIndexCount);
    for (uint32_t _i = 0; _i < args->pCreateInfo_queueFamilyIndexCount; _i++)
        args->pCreateInfo_pQueueFamilyIndices[_i] = r->readU32();
}

struct VnDecode_vkCreateCommandPool {
    uint64_t device;
    uint64_t pCommandPool;
    uint32_t pCreateInfo_flags;
    uint32_t pCreateInfo_queueFamilyIndex;
};

static inline void vn_decode_vkCreateCommandPool(VnStreamReader* r, VnDecode_vkCreateCommandPool* args)
{
    args->device = r->readU64();
    args->pCommandPool = r->readU64();
    args->pCreateInfo_flags = r->readU32();
    args->pCreateInfo_queueFamilyIndex = r->readU32();
}

struct VnDecode_vkCreateDescriptorPool {
    uint64_t device;
    uint64_t pDescriptorPool;
    uint32_t pCreateInfo_flags;
    uint32_t pCreateInfo_maxSets;
    uint32_t pCreateInfo_poolSizeCount;
    std::vector<uint32_t> pCreateInfo_pPoolSizes_type;
    std::vector<uint32_t> pCreateInfo_pPoolSizes_descriptorCount;
};

static inline void vn_decode_vkCreateDescriptorPool(VnStreamReader* r, VnDecode_vkCreateDescriptorPool* args)
{
    args->device = r->readU64();
    args->pDescriptorPool = r->readU64();
    args->pCreateInfo_flags = r->readU32();
    args->pCreateInfo_maxSets = r->readU32();
    args->pCreateInfo_poolSizeCount = r->readU32();
    args->pCreateInfo_pPoolSizes_type.resize(args->pCreateInfo_poolSizeCount);
    args->pCreateInfo_pPoolSizes_descriptorCount.resize(args->pCreateInfo_poolSizeCount);
    for (uint32_t _i = 0; _i < args->pCreateInfo_poolSizeCount; _i++) {
        args->pCreateInfo_pPoolSizes_type[_i] = r->readU32();
        args->pCreateInfo_pPoolSizes_descriptorCount[_i] = r->readU32();
    }
}

struct VnDecode_vkCreateDescriptorSetLayout {
    uint64_t device;
    uint64_t pSetLayout;
    uint32_t pCreateInfo_flags;
    uint32_t pCreateInfo_bindingCount;
    std::vector<uint32_t> pCreateInfo_pBindings_binding;
    std::vector<uint32_t> pCreateInfo_pBindings_descriptorType;
    std::vector<uint32_t> pCreateInfo_pBindings_descriptorCount;
    std::vector<uint32_t> pCreateInfo_pBindings_stageFlags;
};

static inline void vn_decode_vkCreateDescriptorSetLayout(VnStreamReader* r, VnDecode_vkCreateDescriptorSetLayout* args)
{
    args->device = r->readU64();
    args->pSetLayout = r->readU64();
    args->pCreateInfo_flags = r->readU32();
    args->pCreateInfo_bindingCount = r->readU32();
    args->pCreateInfo_pBindings_binding.resize(args->pCreateInfo_bindingCount);
    args->pCreateInfo_pBindings_descriptorType.resize(args->pCreateInfo_bindingCount);
    args->pCreateInfo_pBindings_descriptorCount.resize(args->pCreateInfo_bindingCount);
    args->pCreateInfo_pBindings_stageFlags.resize(args->pCreateInfo_bindingCount);
    for (uint32_t _i = 0; _i < args->pCreateInfo_bindingCount; _i++) {
        args->pCreateInfo_pBindings_binding[_i] = r->readU32();
        args->pCreateInfo_pBindings_descriptorType[_i] = r->readU32();
        args->pCreateInfo_pBindings_descriptorCount[_i] = r->readU32();
        args->pCreateInfo_pBindings_stageFlags[_i] = r->readU32();
    }
}

struct VnDecode_vkCreateFence {
    uint64_t device;
    uint64_t pFence;
    uint32_t pCreateInfo_flags;
};

static inline void vn_decode_vkCreateFence(VnStreamReader* r, VnDecode_vkCreateFence* args)
{
    args->device = r->readU64();
    args->pFence = r->readU64();
    args->pCreateInfo_flags = r->readU32();
}

struct VnDecode_vkCreateFramebuffer {
    uint64_t device;
    uint64_t pFramebuffer;
    uint32_t pCreateInfo_flags;
    uint64_t pCreateInfo_renderPass;
    uint32_t pCreateInfo_attachmentCount;
    std::vector<uint64_t> pCreateInfo_pAttachments;
    uint32_t pCreateInfo_width;
    uint32_t pCreateInfo_height;
    uint32_t pCreateInfo_layers;
};

static inline void vn_decode_vkCreateFramebuffer(VnStreamReader* r, VnDecode_vkCreateFramebuffer* args)
{
    args->device = r->readU64();
    args->pFramebuffer = r->readU64();
    args->pCreateInfo_flags = r->readU32();
    args->pCreateInfo_renderPass = r->readU64();
    args->pCreateInfo_attachmentCount = r->readU32();
    args->pCreateInfo_pAttachments.resize(args->pCreateInfo_attachmentCount);
    for (uint32_t _i = 0; _i < args->pCreateInfo_attachmentCount; _i++)
        args->pCreateInfo_pAttachments[_i] = r->readU64();
    args->pCreateInfo_width = r->readU32();
    args->pCreateInfo_height = r->readU32();
    args->pCreateInfo_layers = r->readU32();
}

struct VnDecode_vkCreateImage {
    uint64_t device;
    uint64_t pImage;
    uint32_t pCreateInfo_flags;
    uint32_t pCreateInfo_imageType;
    uint32_t pCreateInfo_format;
    uint32_t pCreateInfo_extent_width;
    uint32_t pCreateInfo_extent_height;
    uint32_t pCreateInfo_extent_depth;
    uint32_t pCreateInfo_mipLevels;
    uint32_t pCreateInfo_arrayLayers;
    uint32_t pCreateInfo_samples;
    uint32_t pCreateInfo_tiling;
    uint32_t pCreateInfo_usage;
    uint32_t pCreateInfo_sharingMode;
    uint32_t pCreateInfo_queueFamilyIndexCount;
    std::vector<uint32_t> pCreateInfo_pQueueFamilyIndices;
    uint32_t pCreateInfo_initialLayout;
};

static inline void vn_decode_vkCreateImage(VnStreamReader* r, VnDecode_vkCreateImage* args)
{
    args->device = r->readU64();
    args->pImage = r->readU64();
    args->pCreateInfo_flags = r->readU32();
    args->pCreateInfo_imageType = r->readU32();
    args->pCreateInfo_format = r->readU32();
    args->pCreateInfo_extent_width = r->readU32();
    args->pCreateInfo_extent_height = r->readU32();
    args->pCreateInfo_extent_depth = r->readU32();
    args->pCreateInfo_mipLevels = r->readU32();
    args->pCreateInfo_arrayLayers = r->readU32();
    args->pCreateInfo_samples = r->readU32();
    args->pCreateInfo_tiling = r->readU32();
    args->pCreateInfo_usage = r->readU32();
    args->pCreateInfo_sharingMode = r->readU32();
    args->pCreateInfo_queueFamilyIndexCount = r->readU32();
    args->pCreateInfo_pQueueFamilyIndices.resize(args->pCreateInfo_queueFamilyIndexCount);
    for (uint32_t _i = 0; _i < args->pCreateInfo_queueFamilyIndexCount; _i++)
        args->pCreateInfo_pQueueFamilyIndices[_i] = r->readU32();
    args->pCreateInfo_initialLayout = r->readU32();
}

struct VnDecode_vkCreateImageView {
    uint64_t device;
    uint64_t pView;
    uint32_t pCreateInfo_flags;
    uint64_t pCreateInfo_image;
    uint32_t pCreateInfo_viewType;
    uint32_t pCreateInfo_format;
    uint32_t pCreateInfo_components_r;
    uint32_t pCreateInfo_components_g;
    uint32_t pCreateInfo_components_b;
    uint32_t pCreateInfo_components_a;
    uint32_t pCreateInfo_subresourceRange_aspectMask;
    uint32_t pCreateInfo_subresourceRange_baseMipLevel;
    uint32_t pCreateInfo_subresourceRange_levelCount;
    uint32_t pCreateInfo_subresourceRange_baseArrayLayer;
    uint32_t pCreateInfo_subresourceRange_layerCount;
};

static inline void vn_decode_vkCreateImageView(VnStreamReader* r, VnDecode_vkCreateImageView* args)
{
    args->device = r->readU64();
    args->pView = r->readU64();
    args->pCreateInfo_flags = r->readU32();
    args->pCreateInfo_image = r->readU64();
    args->pCreateInfo_viewType = r->readU32();
    args->pCreateInfo_format = r->readU32();
    args->pCreateInfo_components_r = r->readU32();
    args->pCreateInfo_components_g = r->readU32();
    args->pCreateInfo_components_b = r->readU32();
    args->pCreateInfo_components_a = r->readU32();
    args->pCreateInfo_subresourceRange_aspectMask = r->readU32();
    args->pCreateInfo_subresourceRange_baseMipLevel = r->readU32();
    args->pCreateInfo_subresourceRange_levelCount = r->readU32();
    args->pCreateInfo_subresourceRange_baseArrayLayer = r->readU32();
    args->pCreateInfo_subresourceRange_layerCount = r->readU32();
}

struct VnDecode_vkCreatePipelineLayout {
    uint64_t device;
    uint64_t pPipelineLayout;
    uint32_t pCreateInfo_flags;
    uint32_t pCreateInfo_setLayoutCount;
    std::vector<uint64_t> pCreateInfo_pSetLayouts;
    uint32_t pCreateInfo_pushConstantRangeCount;
    std::vector<uint32_t> pCreateInfo_pPushConstantRanges_stageFlags;
    std::vector<uint32_t> pCreateInfo_pPushConstantRanges_offset;
    std::vector<uint32_t> pCreateInfo_pPushConstantRanges_size;
};

static inline void vn_decode_vkCreatePipelineLayout(VnStreamReader* r, VnDecode_vkCreatePipelineLayout* args)
{
    args->device = r->readU64();
    args->pPipelineLayout = r->readU64();
    args->pCreateInfo_flags = r->readU32();
    args->pCreateInfo_setLayoutCount = r->readU32();
    args->pCreateInfo_pSetLayouts.resize(args->pCreateInfo_setLayoutCount);
    for (uint32_t _i = 0; _i < args->pCreateInfo_setLayoutCount; _i++)
        args->pCreateInfo_pSetLayouts[_i] = r->readU64();
    args->pCreateInfo_pushConstantRangeCount = r->readU32();
    args->pCreateInfo_pPushConstantRanges_stageFlags.resize(args->pCreateInfo_pushConstantRangeCount);
    args->pCreateInfo_pPushConstantRanges_offset.resize(args->pCreateInfo_pushConstantRangeCount);
    args->pCreateInfo_pPushConstantRanges_size.resize(args->pCreateInfo_pushConstantRangeCount);
    for (uint32_t _i = 0; _i < args->pCreateInfo_pushConstantRangeCount; _i++) {
        args->pCreateInfo_pPushConstantRanges_stageFlags[_i] = r->readU32();
        args->pCreateInfo_pPushConstantRanges_offset[_i] = r->readU32();
        args->pCreateInfo_pPushConstantRanges_size[_i] = r->readU32();
    }
}

struct VnDecode_vkCreateRenderPass {
    uint64_t device;
    uint64_t pRenderPass;
    uint32_t pCreateInfo_flags;
    uint32_t pCreateInfo_attachmentCount;
    std::vector<uint32_t> pCreateInfo_pAttachments_flags;
    std::vector<uint32_t> pCreateInfo_pAttachments_format;
    std::vector<uint32_t> pCreateInfo_pAttachments_samples;
    std::vector<uint32_t> pCreateInfo_pAttachments_loadOp;
    std::vector<uint32_t> pCreateInfo_pAttachments_storeOp;
    std::vector<uint32_t> pCreateInfo_pAttachments_stencilLoadOp;
    std::vector<uint32_t> pCreateInfo_pAttachments_stencilStoreOp;
    std::vector<uint32_t> pCreateInfo_pAttachments_initialLayout;
    std::vector<uint32_t> pCreateInfo_pAttachments_finalLayout;
    uint32_t pCreateInfo_subpassCount;
    std::vector<uint32_t> pCreateInfo_pSubpasses_flags;
    std::vector<uint32_t> pCreateInfo_pSubpasses_pipelineBindPoint;
    std::vector<uint32_t> pCreateInfo_pSubpasses_inputAttachmentCount;
    std::vector<uint32_t> pCreateInfo_pSubpasses_colorAttachmentCount;
    std::vector<uint32_t> pCreateInfo_pSubpasses_preserveAttachmentCount;
    uint32_t pCreateInfo_dependencyCount;
    std::vector<uint32_t> pCreateInfo_pDependencies_srcSubpass;
    std::vector<uint32_t> pCreateInfo_pDependencies_dstSubpass;
    std::vector<uint32_t> pCreateInfo_pDependencies_srcStageMask;
    std::vector<uint32_t> pCreateInfo_pDependencies_dstStageMask;
    std::vector<uint32_t> pCreateInfo_pDependencies_srcAccessMask;
    std::vector<uint32_t> pCreateInfo_pDependencies_dstAccessMask;
    std::vector<uint32_t> pCreateInfo_pDependencies_dependencyFlags;
};

static inline void vn_decode_vkCreateRenderPass(VnStreamReader* r, VnDecode_vkCreateRenderPass* args)
{
    args->device = r->readU64();
    args->pRenderPass = r->readU64();
    args->pCreateInfo_flags = r->readU32();
    args->pCreateInfo_attachmentCount = r->readU32();
    args->pCreateInfo_pAttachments_flags.resize(args->pCreateInfo_attachmentCount);
    args->pCreateInfo_pAttachments_format.resize(args->pCreateInfo_attachmentCount);
    args->pCreateInfo_pAttachments_samples.resize(args->pCreateInfo_attachmentCount);
    args->pCreateInfo_pAttachments_loadOp.resize(args->pCreateInfo_attachmentCount);
    args->pCreateInfo_pAttachments_storeOp.resize(args->pCreateInfo_attachmentCount);
    args->pCreateInfo_pAttachments_stencilLoadOp.resize(args->pCreateInfo_attachmentCount);
    args->pCreateInfo_pAttachments_stencilStoreOp.resize(args->pCreateInfo_attachmentCount);
    args->pCreateInfo_pAttachments_initialLayout.resize(args->pCreateInfo_attachmentCount);
    args->pCreateInfo_pAttachments_finalLayout.resize(args->pCreateInfo_attachmentCount);
    for (uint32_t _i = 0; _i < args->pCreateInfo_attachmentCount; _i++) {
        args->pCreateInfo_pAttachments_flags[_i] = r->readU32();
        args->pCreateInfo_pAttachments_format[_i] = r->readU32();
        args->pCreateInfo_pAttachments_samples[_i] = r->readU32();
        args->pCreateInfo_pAttachments_loadOp[_i] = r->readU32();
        args->pCreateInfo_pAttachments_storeOp[_i] = r->readU32();
        args->pCreateInfo_pAttachments_stencilLoadOp[_i] = r->readU32();
        args->pCreateInfo_pAttachments_stencilStoreOp[_i] = r->readU32();
        args->pCreateInfo_pAttachments_initialLayout[_i] = r->readU32();
        args->pCreateInfo_pAttachments_finalLayout[_i] = r->readU32();
    }
    args->pCreateInfo_subpassCount = r->readU32();
    args->pCreateInfo_pSubpasses_flags.resize(args->pCreateInfo_subpassCount);
    args->pCreateInfo_pSubpasses_pipelineBindPoint.resize(args->pCreateInfo_subpassCount);
    args->pCreateInfo_pSubpasses_inputAttachmentCount.resize(args->pCreateInfo_subpassCount);
    args->pCreateInfo_pSubpasses_colorAttachmentCount.resize(args->pCreateInfo_subpassCount);
    args->pCreateInfo_pSubpasses_preserveAttachmentCount.resize(args->pCreateInfo_subpassCount);
    for (uint32_t _i = 0; _i < args->pCreateInfo_subpassCount; _i++) {
        args->pCreateInfo_pSubpasses_flags[_i] = r->readU32();
        args->pCreateInfo_pSubpasses_pipelineBindPoint[_i] = r->readU32();
        args->pCreateInfo_pSubpasses_inputAttachmentCount[_i] = r->readU32();
        args->pCreateInfo_pSubpasses_colorAttachmentCount[_i] = r->readU32();
        args->pCreateInfo_pSubpasses_preserveAttachmentCount[_i] = r->readU32();
    }
    args->pCreateInfo_dependencyCount = r->readU32();
    args->pCreateInfo_pDependencies_srcSubpass.resize(args->pCreateInfo_dependencyCount);
    args->pCreateInfo_pDependencies_dstSubpass.resize(args->pCreateInfo_dependencyCount);
    args->pCreateInfo_pDependencies_srcStageMask.resize(args->pCreateInfo_dependencyCount);
    args->pCreateInfo_pDependencies_dstStageMask.resize(args->pCreateInfo_dependencyCount);
    args->pCreateInfo_pDependencies_srcAccessMask.resize(args->pCreateInfo_dependencyCount);
    args->pCreateInfo_pDependencies_dstAccessMask.resize(args->pCreateInfo_dependencyCount);
    args->pCreateInfo_pDependencies_dependencyFlags.resize(args->pCreateInfo_dependencyCount);
    for (uint32_t _i = 0; _i < args->pCreateInfo_dependencyCount; _i++) {
        args->pCreateInfo_pDependencies_srcSubpass[_i] = r->readU32();
        args->pCreateInfo_pDependencies_dstSubpass[_i] = r->readU32();
        args->pCreateInfo_pDependencies_srcStageMask[_i] = r->readU32();
        args->pCreateInfo_pDependencies_dstStageMask[_i] = r->readU32();
        args->pCreateInfo_pDependencies_srcAccessMask[_i] = r->readU32();
        args->pCreateInfo_pDependencies_dstAccessMask[_i] = r->readU32();
        args->pCreateInfo_pDependencies_dependencyFlags[_i] = r->readU32();
    }
}

struct VnDecode_vkCreateSampler {
    uint64_t device;
    uint64_t pSampler;
    uint32_t pCreateInfo_flags;
    uint32_t pCreateInfo_magFilter;
    uint32_t pCreateInfo_minFilter;
    uint32_t pCreateInfo_mipmapMode;
    uint32_t pCreateInfo_addressModeU;
    uint32_t pCreateInfo_addressModeV;
    uint32_t pCreateInfo_addressModeW;
    float pCreateInfo_mipLodBias;
    uint32_t pCreateInfo_anisotropyEnable;
    float pCreateInfo_maxAnisotropy;
    uint32_t pCreateInfo_compareEnable;
    uint32_t pCreateInfo_compareOp;
    float pCreateInfo_minLod;
    float pCreateInfo_maxLod;
    uint32_t pCreateInfo_borderColor;
    uint32_t pCreateInfo_unnormalizedCoordinates;
};

static inline void vn_decode_vkCreateSampler(VnStreamReader* r, VnDecode_vkCreateSampler* args)
{
    args->device = r->readU64();
    args->pSampler = r->readU64();
    args->pCreateInfo_flags = r->readU32();
    args->pCreateInfo_magFilter = r->readU32();
    args->pCreateInfo_minFilter = r->readU32();
    args->pCreateInfo_mipmapMode = r->readU32();
    args->pCreateInfo_addressModeU = r->readU32();
    args->pCreateInfo_addressModeV = r->readU32();
    args->pCreateInfo_addressModeW = r->readU32();
    args->pCreateInfo_mipLodBias = r->readF32();
    args->pCreateInfo_anisotropyEnable = r->readU32();
    args->pCreateInfo_maxAnisotropy = r->readF32();
    args->pCreateInfo_compareEnable = r->readU32();
    args->pCreateInfo_compareOp = r->readU32();
    args->pCreateInfo_minLod = r->readF32();
    args->pCreateInfo_maxLod = r->readF32();
    args->pCreateInfo_borderColor = r->readU32();
    args->pCreateInfo_unnormalizedCoordinates = r->readU32();
}

struct VnDecode_vkCreateSemaphore {
    uint64_t device;
    uint64_t pSemaphore;
    uint32_t pCreateInfo_flags;
};

static inline void vn_decode_vkCreateSemaphore(VnStreamReader* r, VnDecode_vkCreateSemaphore* args)
{
    args->device = r->readU64();
    args->pSemaphore = r->readU64();
    args->pCreateInfo_flags = r->readU32();
}

struct VnDecode_vkDestroyBuffer {
    uint64_t device;
    uint64_t buffer;
};

static inline void vn_decode_vkDestroyBuffer(VnStreamReader* r, VnDecode_vkDestroyBuffer* args)
{
    args->device = r->readU64();
    args->buffer = r->readU64();
}

struct VnDecode_vkDestroyCommandPool {
    uint64_t device;
    uint64_t commandPool;
};

static inline void vn_decode_vkDestroyCommandPool(VnStreamReader* r, VnDecode_vkDestroyCommandPool* args)
{
    args->device = r->readU64();
    args->commandPool = r->readU64();
}

struct VnDecode_vkDestroyDescriptorPool {
    uint64_t device;
    uint64_t descriptorPool;
};

static inline void vn_decode_vkDestroyDescriptorPool(VnStreamReader* r, VnDecode_vkDestroyDescriptorPool* args)
{
    args->device = r->readU64();
    args->descriptorPool = r->readU64();
}

struct VnDecode_vkDestroyDescriptorSetLayout {
    uint64_t device;
    uint64_t descriptorSetLayout;
};

static inline void vn_decode_vkDestroyDescriptorSetLayout(VnStreamReader* r, VnDecode_vkDestroyDescriptorSetLayout* args)
{
    args->device = r->readU64();
    args->descriptorSetLayout = r->readU64();
}

struct VnDecode_vkDestroyFence {
    uint64_t device;
    uint64_t fence;
};

static inline void vn_decode_vkDestroyFence(VnStreamReader* r, VnDecode_vkDestroyFence* args)
{
    args->device = r->readU64();
    args->fence = r->readU64();
}

struct VnDecode_vkDestroyFramebuffer {
    uint64_t device;
    uint64_t framebuffer;
};

static inline void vn_decode_vkDestroyFramebuffer(VnStreamReader* r, VnDecode_vkDestroyFramebuffer* args)
{
    args->device = r->readU64();
    args->framebuffer = r->readU64();
}

struct VnDecode_vkDestroyImage {
    uint64_t device;
    uint64_t image;
};

static inline void vn_decode_vkDestroyImage(VnStreamReader* r, VnDecode_vkDestroyImage* args)
{
    args->device = r->readU64();
    args->image = r->readU64();
}

struct VnDecode_vkDestroyImageView {
    uint64_t device;
    uint64_t imageView;
};

static inline void vn_decode_vkDestroyImageView(VnStreamReader* r, VnDecode_vkDestroyImageView* args)
{
    args->device = r->readU64();
    args->imageView = r->readU64();
}

struct VnDecode_vkDestroyPipeline {
    uint64_t device;
    uint64_t pipeline;
};

static inline void vn_decode_vkDestroyPipeline(VnStreamReader* r, VnDecode_vkDestroyPipeline* args)
{
    args->device = r->readU64();
    args->pipeline = r->readU64();
}

struct VnDecode_vkDestroyPipelineLayout {
    uint64_t device;
    uint64_t pipelineLayout;
};

static inline void vn_decode_vkDestroyPipelineLayout(VnStreamReader* r, VnDecode_vkDestroyPipelineLayout* args)
{
    args->device = r->readU64();
    args->pipelineLayout = r->readU64();
}

struct VnDecode_vkDestroyRenderPass {
    uint64_t device;
    uint64_t renderPass;
};

static inline void vn_decode_vkDestroyRenderPass(VnStreamReader* r, VnDecode_vkDestroyRenderPass* args)
{
    args->device = r->readU64();
    args->renderPass = r->readU64();
}

struct VnDecode_vkDestroySampler {
    uint64_t device;
    uint64_t sampler;
};

static inline void vn_decode_vkDestroySampler(VnStreamReader* r, VnDecode_vkDestroySampler* args)
{
    args->device = r->readU64();
    args->sampler = r->readU64();
}

struct VnDecode_vkDestroySemaphore {
    uint64_t device;
    uint64_t semaphore;
};

static inline void vn_decode_vkDestroySemaphore(VnStreamReader* r, VnDecode_vkDestroySemaphore* args)
{
    args->device = r->readU64();
    args->semaphore = r->readU64();
}

struct VnDecode_vkDestroyShaderModule {
    uint64_t device;
    uint64_t shaderModule;
};

static inline void vn_decode_vkDestroyShaderModule(VnStreamReader* r, VnDecode_vkDestroyShaderModule* args)
{
    args->device = r->readU64();
    args->shaderModule = r->readU64();
}

struct VnDecode_vkEndCommandBuffer {
    uint64_t commandBuffer;
};

static inline void vn_decode_vkEndCommandBuffer(VnStreamReader* r, VnDecode_vkEndCommandBuffer* args)
{
    args->commandBuffer = r->readU64();
}

struct VnDecode_vkFreeMemory {
    uint64_t device;
    uint64_t memory;
};

static inline void vn_decode_vkFreeMemory(VnStreamReader* r, VnDecode_vkFreeMemory* args)
{
    args->device = r->readU64();
    args->memory = r->readU64();
}

struct VnDecode_vkQueueSubmit {
    uint64_t queue;
    uint64_t fence;
    uint32_t submitCount;
    uint32_t submitCount;
    std::vector<uint32_t> pSubmits_waitSemaphoreCount;
    std::vector<uint32_t> pSubmits_commandBufferCount;
    std::vector<uint32_t> pSubmits_signalSemaphoreCount;
};

static inline void vn_decode_vkQueueSubmit(VnStreamReader* r, VnDecode_vkQueueSubmit* args)
{
    args->queue = r->readU64();
    args->fence = r->readU64();
    args->submitCount = r->readU32();
    args->submitCount = r->readU32();
    args->pSubmits_waitSemaphoreCount.resize(args->submitCount);
    args->pSubmits_commandBufferCount.resize(args->submitCount);
    args->pSubmits_signalSemaphoreCount.resize(args->submitCount);
    for (uint32_t _i = 0; _i < args->submitCount; _i++) {
        args->pSubmits_waitSemaphoreCount[_i] = r->readU32();
        args->pSubmits_commandBufferCount[_i] = r->readU32();
        args->pSubmits_signalSemaphoreCount[_i] = r->readU32();
    }
}

struct VnDecode_vkResetFences {
    uint64_t device;
    uint32_t fenceCount;
    std::vector<uint64_t> pFences;
};

static inline void vn_decode_vkResetFences(VnStreamReader* r, VnDecode_vkResetFences* args)
{
    args->device = r->readU64();
    args->fenceCount = r->readU32();
    args->pFences.resize(args->fenceCount);
    for (uint32_t i = 0; i < args->fenceCount; i++)
        args->pFences[i] = r->readU64();
}

struct VnDecode_vkUpdateDescriptorSets {
    uint64_t device;
    uint32_t descriptorWriteCount;
    uint32_t descriptorWriteCount;
    std::vector<uint64_t> pDescriptorWrites_dstSet;
    std::vector<uint32_t> pDescriptorWrites_dstBinding;
    std::vector<uint32_t> pDescriptorWrites_dstArrayElement;
    std::vector<uint32_t> pDescriptorWrites_descriptorCount;
    std::vector<uint32_t> pDescriptorWrites_descriptorType;
    uint32_t descriptorCopyCount;
    uint32_t descriptorCopyCount;
    std::vector<uint64_t> pDescriptorCopies_srcSet;
    std::vector<uint32_t> pDescriptorCopies_srcBinding;
    std::vector<uint32_t> pDescriptorCopies_srcArrayElement;
    std::vector<uint64_t> pDescriptorCopies_dstSet;
    std::vector<uint32_t> pDescriptorCopies_dstBinding;
    std::vector<uint32_t> pDescriptorCopies_dstArrayElement;
    std::vector<uint32_t> pDescriptorCopies_descriptorCount;
};

static inline void vn_decode_vkUpdateDescriptorSets(VnStreamReader* r, VnDecode_vkUpdateDescriptorSets* args)
{
    args->device = r->readU64();
    args->descriptorWriteCount = r->readU32();
    args->descriptorWriteCount = r->readU32();
    args->pDescriptorWrites_dstSet.resize(args->descriptorWriteCount);
    args->pDescriptorWrites_dstBinding.resize(args->descriptorWriteCount);
    args->pDescriptorWrites_dstArrayElement.resize(args->descriptorWriteCount);
    args->pDescriptorWrites_descriptorCount.resize(args->descriptorWriteCount);
    args->pDescriptorWrites_descriptorType.resize(args->descriptorWriteCount);
    for (uint32_t _i = 0; _i < args->descriptorWriteCount; _i++) {
        args->pDescriptorWrites_dstSet[_i] = r->readU64();
        args->pDescriptorWrites_dstBinding[_i] = r->readU32();
        args->pDescriptorWrites_dstArrayElement[_i] = r->readU32();
        args->pDescriptorWrites_descriptorCount[_i] = r->readU32();
        args->pDescriptorWrites_descriptorType[_i] = r->readU32();
    }
    args->descriptorCopyCount = r->readU32();
    args->descriptorCopyCount = r->readU32();
    args->pDescriptorCopies_srcSet.resize(args->descriptorCopyCount);
    args->pDescriptorCopies_srcBinding.resize(args->descriptorCopyCount);
    args->pDescriptorCopies_srcArrayElement.resize(args->descriptorCopyCount);
    args->pDescriptorCopies_dstSet.resize(args->descriptorCopyCount);
    args->pDescriptorCopies_dstBinding.resize(args->descriptorCopyCount);
    args->pDescriptorCopies_dstArrayElement.resize(args->descriptorCopyCount);
    args->pDescriptorCopies_descriptorCount.resize(args->descriptorCopyCount);
    for (uint32_t _i = 0; _i < args->descriptorCopyCount; _i++) {
        args->pDescriptorCopies_srcSet[_i] = r->readU64();
        args->pDescriptorCopies_srcBinding[_i] = r->readU32();
        args->pDescriptorCopies_srcArrayElement[_i] = r->readU32();
        args->pDescriptorCopies_dstSet[_i] = r->readU64();
        args->pDescriptorCopies_dstBinding[_i] = r->readU32();
        args->pDescriptorCopies_dstArrayElement[_i] = r->readU32();
        args->pDescriptorCopies_descriptorCount[_i] = r->readU32();
    }
}

struct VnDecode_vkWaitForFences {
    uint64_t device;
    uint32_t fenceCount;
    std::vector<uint64_t> pFences;
    uint32_t waitAll;
    uint64_t timeout;
};

static inline void vn_decode_vkWaitForFences(VnStreamReader* r, VnDecode_vkWaitForFences* args)
{
    args->device = r->readU64();
    args->fenceCount = r->readU32();
    args->pFences.resize(args->fenceCount);
    for (uint32_t i = 0; i < args->fenceCount; i++)
        args->pFences[i] = r->readU64();
    args->waitAll = r->readU32();
    args->timeout = r->readU64();
}
