// Auto-generated by codegen/bridge_codegen.py — DO NOT EDIT
// Source: vk.xml (Venus protocol standard)
#pragma once

#include "vn_stream.h"

static inline void vn_encode_vkBindBufferMemory(VnStreamWriter* w
    , uint64_t device
    , uint64_t buffer
    , uint64_t memory
    , uint64_t memoryOffset
)
{
    w->writeU64(device);
    w->writeU64(buffer);
    w->writeU64(memory);
    w->writeU64(memoryOffset);
}

static inline void vn_encode_vkBindImageMemory(VnStreamWriter* w
    , uint64_t device
    , uint64_t image
    , uint64_t memory
    , uint64_t memoryOffset
)
{
    w->writeU64(device);
    w->writeU64(image);
    w->writeU64(memory);
    w->writeU64(memoryOffset);
}

static inline void vn_encode_vkCmdBindDescriptorSets(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t pipelineBindPoint
    , uint64_t layout
    , uint32_t firstSet
    , uint32_t descriptorSetCount
    , const uint64_t* pDescriptorSets
    , uint32_t dynamicOffsetCount
    , const uint32_t* pDynamicOffsets
)
{
    w->writeU64(commandBuffer);
    w->writeU32(pipelineBindPoint);
    w->writeU64(layout);
    w->writeU32(firstSet);
    w->writeU32(descriptorSetCount);
    for (uint32_t i = 0; i < descriptorSetCount; i++)
        w->writeU64(pDescriptorSets[i]);
    w->writeU32(dynamicOffsetCount);
    for (uint32_t i = 0; i < dynamicOffsetCount; i++)
        w->writeU32(pDynamicOffsets[i]);
}

static inline void vn_encode_vkCmdBindIndexBuffer(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint64_t buffer
    , uint64_t offset
    , uint32_t indexType
)
{
    w->writeU64(commandBuffer);
    w->writeU64(buffer);
    w->writeU64(offset);
    w->writeU32(indexType);
}

static inline void vn_encode_vkCmdBindPipeline(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t pipelineBindPoint
    , uint64_t pipeline
)
{
    w->writeU64(commandBuffer);
    w->writeU32(pipelineBindPoint);
    w->writeU64(pipeline);
}

static inline void vn_encode_vkCmdBindVertexBuffers(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t firstBinding
    , uint32_t bindingCount
    , const uint64_t* pBuffers
    , const uint64_t* pOffsets
)
{
    w->writeU64(commandBuffer);
    w->writeU32(firstBinding);
    w->writeU32(bindingCount);
    for (uint32_t i = 0; i < bindingCount; i++)
        w->writeU64(pBuffers[i]);
    for (uint32_t i = 0; i < bindingCount; i++)
        w->writeU64(pOffsets[i]);
}

static inline void vn_encode_vkCmdDraw(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t vertexCount
    , uint32_t instanceCount
    , uint32_t firstVertex
    , uint32_t firstInstance
)
{
    w->writeU64(commandBuffer);
    w->writeU32(vertexCount);
    w->writeU32(instanceCount);
    w->writeU32(firstVertex);
    w->writeU32(firstInstance);
}

static inline void vn_encode_vkCmdDrawIndexed(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t indexCount
    , uint32_t instanceCount
    , uint32_t firstIndex
    , int32_t vertexOffset
    , uint32_t firstInstance
)
{
    w->writeU64(commandBuffer);
    w->writeU32(indexCount);
    w->writeU32(instanceCount);
    w->writeU32(firstIndex);
    w->writeI32(vertexOffset);
    w->writeU32(firstInstance);
}

static inline void vn_encode_vkCmdEndRenderPass(VnStreamWriter* w
    , uint64_t commandBuffer
)
{
    w->writeU64(commandBuffer);
}

static inline void vn_encode_vkCmdEndRendering(VnStreamWriter* w
    , uint64_t commandBuffer
)
{
    w->writeU64(commandBuffer);
}

static inline void vn_encode_vkCmdPushConstants(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint64_t layout
    , uint32_t stageFlags
    , uint32_t offset
    , uint32_t size
    , const void* pValues
)
{
    w->writeU64(commandBuffer);
    w->writeU64(layout);
    w->writeU32(stageFlags);
    w->writeU32(offset);
    w->writeU32(size);
    w->writeBytes(pValues, size);
}

static inline void vn_encode_vkCmdSetCullMode(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t cullMode
)
{
    w->writeU64(commandBuffer);
    w->writeU32(cullMode);
}

static inline void vn_encode_vkCmdSetDepthBiasEnable(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t depthBiasEnable
)
{
    w->writeU64(commandBuffer);
    w->writeU32(depthBiasEnable);
}

static inline void vn_encode_vkCmdSetDepthBoundsTestEnable(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t depthBoundsTestEnable
)
{
    w->writeU64(commandBuffer);
    w->writeU32(depthBoundsTestEnable);
}

static inline void vn_encode_vkCmdSetDepthCompareOp(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t depthCompareOp
)
{
    w->writeU64(commandBuffer);
    w->writeU32(depthCompareOp);
}

static inline void vn_encode_vkCmdSetDepthTestEnable(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t depthTestEnable
)
{
    w->writeU64(commandBuffer);
    w->writeU32(depthTestEnable);
}

static inline void vn_encode_vkCmdSetDepthWriteEnable(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t depthWriteEnable
)
{
    w->writeU64(commandBuffer);
    w->writeU32(depthWriteEnable);
}

static inline void vn_encode_vkCmdSetFrontFace(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint32_t frontFace
)
{
    w->writeU64(commandBuffer);
    w->writeU32(frontFace);
}

static inline void vn_encode_vkCmdUpdateBuffer(VnStreamWriter* w
    , uint64_t commandBuffer
    , uint64_t dstBuffer
    , uint64_t dstOffset
    , uint64_t dataSize
    , const void* pData
)
{
    w->writeU64(commandBuffer);
    w->writeU64(dstBuffer);
    w->writeU64(dstOffset);
    w->writeU64(dataSize);
    w->writeBytes(pData, dataSize);
}

static inline void vn_encode_vkDestroyBuffer(VnStreamWriter* w
    , uint64_t device
    , uint64_t buffer
)
{
    w->writeU64(device);
    w->writeU64(buffer);
}

static inline void vn_encode_vkDestroyCommandPool(VnStreamWriter* w
    , uint64_t device
    , uint64_t commandPool
)
{
    w->writeU64(device);
    w->writeU64(commandPool);
}

static inline void vn_encode_vkDestroyDescriptorPool(VnStreamWriter* w
    , uint64_t device
    , uint64_t descriptorPool
)
{
    w->writeU64(device);
    w->writeU64(descriptorPool);
}

static inline void vn_encode_vkDestroyDescriptorSetLayout(VnStreamWriter* w
    , uint64_t device
    , uint64_t descriptorSetLayout
)
{
    w->writeU64(device);
    w->writeU64(descriptorSetLayout);
}

static inline void vn_encode_vkDestroyFence(VnStreamWriter* w
    , uint64_t device
    , uint64_t fence
)
{
    w->writeU64(device);
    w->writeU64(fence);
}

static inline void vn_encode_vkDestroyFramebuffer(VnStreamWriter* w
    , uint64_t device
    , uint64_t framebuffer
)
{
    w->writeU64(device);
    w->writeU64(framebuffer);
}

static inline void vn_encode_vkDestroyImage(VnStreamWriter* w
    , uint64_t device
    , uint64_t image
)
{
    w->writeU64(device);
    w->writeU64(image);
}

static inline void vn_encode_vkDestroyImageView(VnStreamWriter* w
    , uint64_t device
    , uint64_t imageView
)
{
    w->writeU64(device);
    w->writeU64(imageView);
}

static inline void vn_encode_vkDestroyPipeline(VnStreamWriter* w
    , uint64_t device
    , uint64_t pipeline
)
{
    w->writeU64(device);
    w->writeU64(pipeline);
}

static inline void vn_encode_vkDestroyPipelineLayout(VnStreamWriter* w
    , uint64_t device
    , uint64_t pipelineLayout
)
{
    w->writeU64(device);
    w->writeU64(pipelineLayout);
}

static inline void vn_encode_vkDestroyRenderPass(VnStreamWriter* w
    , uint64_t device
    , uint64_t renderPass
)
{
    w->writeU64(device);
    w->writeU64(renderPass);
}

static inline void vn_encode_vkDestroySampler(VnStreamWriter* w
    , uint64_t device
    , uint64_t sampler
)
{
    w->writeU64(device);
    w->writeU64(sampler);
}

static inline void vn_encode_vkDestroySemaphore(VnStreamWriter* w
    , uint64_t device
    , uint64_t semaphore
)
{
    w->writeU64(device);
    w->writeU64(semaphore);
}

static inline void vn_encode_vkDestroyShaderModule(VnStreamWriter* w
    , uint64_t device
    , uint64_t shaderModule
)
{
    w->writeU64(device);
    w->writeU64(shaderModule);
}

static inline void vn_encode_vkEndCommandBuffer(VnStreamWriter* w
    , uint64_t commandBuffer
)
{
    w->writeU64(commandBuffer);
}

static inline void vn_encode_vkFreeMemory(VnStreamWriter* w
    , uint64_t device
    , uint64_t memory
)
{
    w->writeU64(device);
    w->writeU64(memory);
}

static inline void vn_encode_vkResetFences(VnStreamWriter* w
    , uint64_t device
    , uint32_t fenceCount
    , const uint64_t* pFences
)
{
    w->writeU64(device);
    w->writeU32(fenceCount);
    for (uint32_t i = 0; i < fenceCount; i++)
        w->writeU64(pFences[i]);
}

static inline void vn_encode_vkWaitForFences(VnStreamWriter* w
    , uint64_t device
    , uint32_t fenceCount
    , const uint64_t* pFences
    , uint32_t waitAll
    , uint64_t timeout
)
{
    w->writeU64(device);
    w->writeU32(fenceCount);
    for (uint32_t i = 0; i < fenceCount; i++)
        w->writeU64(pFences[i]);
    w->writeU32(waitAll);
    w->writeU64(timeout);
}

// ── Not yet generated (complex parameter types) ──
// TODO: vkAllocateCommandBuffers — complex: VkCommandBufferAllocateInfo* pAllocateInfo, VkCommandBuffer* pCommandBuffers
// TODO: vkAllocateDescriptorSets — complex: VkDescriptorSetAllocateInfo* pAllocateInfo, VkDescriptorSet* pDescriptorSets
// TODO: vkAllocateMemory — complex: VkMemoryAllocateInfo* pAllocateInfo, VkDeviceMemory* pMemory
// TODO: vkBeginCommandBuffer — complex: VkCommandBufferBeginInfo* pBeginInfo
// TODO: vkCmdBeginRenderPass — complex: VkRenderPassBeginInfo* pRenderPassBegin
// TODO: vkCmdBeginRendering — complex: VkRenderingInfo* pRenderingInfo
// TODO: vkCmdBindVertexBuffers2 — complex: VkDeviceSize* pSizes, VkDeviceSize* pStrides
// TODO: vkCmdClearAttachments — complex: VkClearAttachment* pAttachments, VkClearRect* pRects
// TODO: vkCmdClearColorImage — complex: VkClearColorValue* pColor, VkImageSubresourceRange* pRanges
// TODO: vkCmdCopyBuffer — complex: VkBufferCopy* pRegions
// TODO: vkCmdCopyBufferToImage — complex: VkBufferImageCopy* pRegions
// TODO: vkCmdPipelineBarrier — complex: VkMemoryBarrier* pMemoryBarriers, VkBufferMemoryBarrier* pBufferMemoryBarriers, VkImageMemoryBarrier* pImageMemoryBarriers
// TODO: vkCmdSetScissor — complex: VkRect2D* pScissors
// TODO: vkCmdSetViewport — complex: VkViewport* pViewports
// TODO: vkCreateBuffer — complex: VkBufferCreateInfo* pCreateInfo, VkBuffer* pBuffer
// TODO: vkCreateCommandPool — complex: VkCommandPoolCreateInfo* pCreateInfo, VkCommandPool* pCommandPool
// TODO: vkCreateDescriptorPool — complex: VkDescriptorPoolCreateInfo* pCreateInfo, VkDescriptorPool* pDescriptorPool
// TODO: vkCreateDescriptorSetLayout — complex: VkDescriptorSetLayoutCreateInfo* pCreateInfo, VkDescriptorSetLayout* pSetLayout
// TODO: vkCreateFence — complex: VkFenceCreateInfo* pCreateInfo, VkFence* pFence
// TODO: vkCreateFramebuffer — complex: VkFramebufferCreateInfo* pCreateInfo, VkFramebuffer* pFramebuffer
// TODO: vkCreateGraphicsPipelines — complex: VkGraphicsPipelineCreateInfo* pCreateInfos
// TODO: vkCreateImage — complex: VkImageCreateInfo* pCreateInfo, VkImage* pImage
// TODO: vkCreateImageView — complex: VkImageViewCreateInfo* pCreateInfo, VkImageView* pView
// TODO: vkCreatePipelineLayout — complex: VkPipelineLayoutCreateInfo* pCreateInfo, VkPipelineLayout* pPipelineLayout
// TODO: vkCreateRenderPass — complex: VkRenderPassCreateInfo* pCreateInfo, VkRenderPass* pRenderPass
// TODO: vkCreateSampler — complex: VkSamplerCreateInfo* pCreateInfo, VkSampler* pSampler
// TODO: vkCreateSemaphore — complex: VkSemaphoreCreateInfo* pCreateInfo, VkSemaphore* pSemaphore
// TODO: vkCreateShaderModule — complex: VkShaderModuleCreateInfo* pCreateInfo, VkShaderModule* pShaderModule
// TODO: vkQueueSubmit — complex: VkSubmitInfo* pSubmits
// TODO: vkUpdateDescriptorSets — complex: VkWriteDescriptorSet* pDescriptorWrites, VkCopyDescriptorSet* pDescriptorCopies
