// Auto-generated by codegen/bridge_codegen.py — DO NOT EDIT
// Source: vk.xml (Venus protocol standard)
#pragma once

#include "vn_stream.h"
#include <vector>

struct VnDecode_vkAllocateMemory {
    uint64_t device;
    uint64_t pMemory;
    uint64_t pAllocateInfo_allocationSize;
    uint32_t pAllocateInfo_memoryTypeIndex;
};

static inline void vn_decode_vkAllocateMemory(VnStreamReader* r, VnDecode_vkAllocateMemory* args)
{
    args->device = r->readU64();
    args->pMemory = r->readU64();
    args->pAllocateInfo_allocationSize = r->readU64();
    args->pAllocateInfo_memoryTypeIndex = r->readU32();
}

struct VnDecode_vkBeginCommandBuffer {
    uint64_t commandBuffer;
    uint32_t pBeginInfo_flags;
};

static inline void vn_decode_vkBeginCommandBuffer(VnStreamReader* r, VnDecode_vkBeginCommandBuffer* args)
{
    args->commandBuffer = r->readU64();
    args->pBeginInfo_flags = r->readU32();
}

struct VnDecode_vkBindBufferMemory {
    uint64_t device;
    uint64_t buffer;
    uint64_t memory;
    uint64_t memoryOffset;
};

static inline void vn_decode_vkBindBufferMemory(VnStreamReader* r, VnDecode_vkBindBufferMemory* args)
{
    args->device = r->readU64();
    args->buffer = r->readU64();
    args->memory = r->readU64();
    args->memoryOffset = r->readU64();
}

struct VnDecode_vkBindImageMemory {
    uint64_t device;
    uint64_t image;
    uint64_t memory;
    uint64_t memoryOffset;
};

static inline void vn_decode_vkBindImageMemory(VnStreamReader* r, VnDecode_vkBindImageMemory* args)
{
    args->device = r->readU64();
    args->image = r->readU64();
    args->memory = r->readU64();
    args->memoryOffset = r->readU64();
}

struct VnDecode_vkCmdBindDescriptorSets {
    uint64_t commandBuffer;
    uint64_t layout;
    uint32_t pipelineBindPoint;
    uint32_t firstSet;
    uint32_t descriptorSetCount;
    std::vector<uint64_t> pDescriptorSets;
    uint32_t dynamicOffsetCount;
    std::vector<uint32_t> pDynamicOffsets;
};

static inline void vn_decode_vkCmdBindDescriptorSets(VnStreamReader* r, VnDecode_vkCmdBindDescriptorSets* args)
{
    args->commandBuffer = r->readU64();
    args->layout = r->readU64();
    args->pipelineBindPoint = r->readU32();
    args->firstSet = r->readU32();
    args->descriptorSetCount = r->readU32();
    args->pDescriptorSets.resize(args->descriptorSetCount);
    for (uint32_t i = 0; i < args->descriptorSetCount; i++)
        args->pDescriptorSets[i] = r->readU64();
    args->dynamicOffsetCount = r->readU32();
    args->pDynamicOffsets.resize(args->dynamicOffsetCount);
    for (uint32_t i = 0; i < args->dynamicOffsetCount; i++)
        args->pDynamicOffsets[i] = r->readU32();
}

struct VnDecode_vkCmdBindIndexBuffer {
    uint64_t commandBuffer;
    uint64_t buffer;
    uint64_t offset;
    uint32_t indexType;
};

static inline void vn_decode_vkCmdBindIndexBuffer(VnStreamReader* r, VnDecode_vkCmdBindIndexBuffer* args)
{
    args->commandBuffer = r->readU64();
    args->buffer = r->readU64();
    args->offset = r->readU64();
    args->indexType = r->readU32();
}

struct VnDecode_vkCmdBindPipeline {
    uint64_t commandBuffer;
    uint64_t pipeline;
    uint32_t pipelineBindPoint;
};

static inline void vn_decode_vkCmdBindPipeline(VnStreamReader* r, VnDecode_vkCmdBindPipeline* args)
{
    args->commandBuffer = r->readU64();
    args->pipeline = r->readU64();
    args->pipelineBindPoint = r->readU32();
}

struct VnDecode_vkCmdBindVertexBuffers {
    uint64_t commandBuffer;
    uint32_t firstBinding;
    uint32_t bindingCount;
    std::vector<uint64_t> pBuffers;
    std::vector<uint64_t> pOffsets;
};

static inline void vn_decode_vkCmdBindVertexBuffers(VnStreamReader* r, VnDecode_vkCmdBindVertexBuffers* args)
{
    args->commandBuffer = r->readU64();
    args->firstBinding = r->readU32();
    args->bindingCount = r->readU32();
    args->pBuffers.resize(args->bindingCount);
    for (uint32_t i = 0; i < args->bindingCount; i++)
        args->pBuffers[i] = r->readU64();
    args->pOffsets.resize(args->bindingCount);
    for (uint32_t i = 0; i < args->bindingCount; i++)
        args->pOffsets[i] = r->readU64();
}

struct VnDecode_vkCmdDraw {
    uint64_t commandBuffer;
    uint32_t vertexCount;
    uint32_t instanceCount;
    uint32_t firstVertex;
    uint32_t firstInstance;
};

static inline void vn_decode_vkCmdDraw(VnStreamReader* r, VnDecode_vkCmdDraw* args)
{
    args->commandBuffer = r->readU64();
    args->vertexCount = r->readU32();
    args->instanceCount = r->readU32();
    args->firstVertex = r->readU32();
    args->firstInstance = r->readU32();
}

struct VnDecode_vkCmdDrawIndexed {
    uint64_t commandBuffer;
    uint32_t indexCount;
    uint32_t instanceCount;
    uint32_t firstIndex;
    int32_t vertexOffset;
    uint32_t firstInstance;
};

static inline void vn_decode_vkCmdDrawIndexed(VnStreamReader* r, VnDecode_vkCmdDrawIndexed* args)
{
    args->commandBuffer = r->readU64();
    args->indexCount = r->readU32();
    args->instanceCount = r->readU32();
    args->firstIndex = r->readU32();
    args->vertexOffset = r->readI32();
    args->firstInstance = r->readU32();
}

struct VnDecode_vkCmdEndRenderPass {
    uint64_t commandBuffer;
};

static inline void vn_decode_vkCmdEndRenderPass(VnStreamReader* r, VnDecode_vkCmdEndRenderPass* args)
{
    args->commandBuffer = r->readU64();
}

struct VnDecode_vkCmdEndRendering {
    uint64_t commandBuffer;
};

static inline void vn_decode_vkCmdEndRendering(VnStreamReader* r, VnDecode_vkCmdEndRendering* args)
{
    args->commandBuffer = r->readU64();
}

struct VnDecode_vkCmdPushConstants {
    uint64_t commandBuffer;
    uint64_t layout;
    uint32_t stageFlags;
    uint32_t offset;
    uint32_t size;
    std::vector<uint8_t> pValues;
};

static inline void vn_decode_vkCmdPushConstants(VnStreamReader* r, VnDecode_vkCmdPushConstants* args)
{
    args->commandBuffer = r->readU64();
    args->layout = r->readU64();
    args->stageFlags = r->readU32();
    args->offset = r->readU32();
    args->size = r->readU32();
    args->pValues.resize(args->size);
    r->readBytes(args->pValues.data(), args->size);
}

struct VnDecode_vkCmdSetCullMode {
    uint64_t commandBuffer;
    uint32_t cullMode;
};

static inline void vn_decode_vkCmdSetCullMode(VnStreamReader* r, VnDecode_vkCmdSetCullMode* args)
{
    args->commandBuffer = r->readU64();
    args->cullMode = r->readU32();
}

struct VnDecode_vkCmdSetDepthBiasEnable {
    uint64_t commandBuffer;
    uint32_t depthBiasEnable;
};

static inline void vn_decode_vkCmdSetDepthBiasEnable(VnStreamReader* r, VnDecode_vkCmdSetDepthBiasEnable* args)
{
    args->commandBuffer = r->readU64();
    args->depthBiasEnable = r->readU32();
}

struct VnDecode_vkCmdSetDepthBoundsTestEnable {
    uint64_t commandBuffer;
    uint32_t depthBoundsTestEnable;
};

static inline void vn_decode_vkCmdSetDepthBoundsTestEnable(VnStreamReader* r, VnDecode_vkCmdSetDepthBoundsTestEnable* args)
{
    args->commandBuffer = r->readU64();
    args->depthBoundsTestEnable = r->readU32();
}

struct VnDecode_vkCmdSetDepthCompareOp {
    uint64_t commandBuffer;
    uint32_t depthCompareOp;
};

static inline void vn_decode_vkCmdSetDepthCompareOp(VnStreamReader* r, VnDecode_vkCmdSetDepthCompareOp* args)
{
    args->commandBuffer = r->readU64();
    args->depthCompareOp = r->readU32();
}

struct VnDecode_vkCmdSetDepthTestEnable {
    uint64_t commandBuffer;
    uint32_t depthTestEnable;
};

static inline void vn_decode_vkCmdSetDepthTestEnable(VnStreamReader* r, VnDecode_vkCmdSetDepthTestEnable* args)
{
    args->commandBuffer = r->readU64();
    args->depthTestEnable = r->readU32();
}

struct VnDecode_vkCmdSetDepthWriteEnable {
    uint64_t commandBuffer;
    uint32_t depthWriteEnable;
};

static inline void vn_decode_vkCmdSetDepthWriteEnable(VnStreamReader* r, VnDecode_vkCmdSetDepthWriteEnable* args)
{
    args->commandBuffer = r->readU64();
    args->depthWriteEnable = r->readU32();
}

struct VnDecode_vkCmdSetFrontFace {
    uint64_t commandBuffer;
    uint32_t frontFace;
};

static inline void vn_decode_vkCmdSetFrontFace(VnStreamReader* r, VnDecode_vkCmdSetFrontFace* args)
{
    args->commandBuffer = r->readU64();
    args->frontFace = r->readU32();
}

struct VnDecode_vkCmdUpdateBuffer {
    uint64_t commandBuffer;
    uint64_t dstBuffer;
    uint64_t dstOffset;
    uint64_t dataSize;
    std::vector<uint8_t> pData;
};

static inline void vn_decode_vkCmdUpdateBuffer(VnStreamReader* r, VnDecode_vkCmdUpdateBuffer* args)
{
    args->commandBuffer = r->readU64();
    args->dstBuffer = r->readU64();
    args->dstOffset = r->readU64();
    args->dataSize = r->readU64();
    args->pData.resize(args->dataSize);
    r->readBytes(args->pData.data(), args->dataSize);
}

struct VnDecode_vkCreateCommandPool {
    uint64_t device;
    uint64_t pCommandPool;
    uint32_t pCreateInfo_flags;
    uint32_t pCreateInfo_queueFamilyIndex;
};

static inline void vn_decode_vkCreateCommandPool(VnStreamReader* r, VnDecode_vkCreateCommandPool* args)
{
    args->device = r->readU64();
    args->pCommandPool = r->readU64();
    args->pCreateInfo_flags = r->readU32();
    args->pCreateInfo_queueFamilyIndex = r->readU32();
}

struct VnDecode_vkCreateFence {
    uint64_t device;
    uint64_t pFence;
    uint32_t pCreateInfo_flags;
};

static inline void vn_decode_vkCreateFence(VnStreamReader* r, VnDecode_vkCreateFence* args)
{
    args->device = r->readU64();
    args->pFence = r->readU64();
    args->pCreateInfo_flags = r->readU32();
}

struct VnDecode_vkCreateImageView {
    uint64_t device;
    uint64_t pView;
    uint32_t pCreateInfo_flags;
    uint64_t pCreateInfo_image;
    uint32_t pCreateInfo_viewType;
    uint32_t pCreateInfo_format;
    uint32_t pCreateInfo_components_r;
    uint32_t pCreateInfo_components_g;
    uint32_t pCreateInfo_components_b;
    uint32_t pCreateInfo_components_a;
    uint32_t pCreateInfo_subresourceRange_aspectMask;
    uint32_t pCreateInfo_subresourceRange_baseMipLevel;
    uint32_t pCreateInfo_subresourceRange_levelCount;
    uint32_t pCreateInfo_subresourceRange_baseArrayLayer;
    uint32_t pCreateInfo_subresourceRange_layerCount;
};

static inline void vn_decode_vkCreateImageView(VnStreamReader* r, VnDecode_vkCreateImageView* args)
{
    args->device = r->readU64();
    args->pView = r->readU64();
    args->pCreateInfo_flags = r->readU32();
    args->pCreateInfo_image = r->readU64();
    args->pCreateInfo_viewType = r->readU32();
    args->pCreateInfo_format = r->readU32();
    args->pCreateInfo_components_r = r->readU32();
    args->pCreateInfo_components_g = r->readU32();
    args->pCreateInfo_components_b = r->readU32();
    args->pCreateInfo_components_a = r->readU32();
    args->pCreateInfo_subresourceRange_aspectMask = r->readU32();
    args->pCreateInfo_subresourceRange_baseMipLevel = r->readU32();
    args->pCreateInfo_subresourceRange_levelCount = r->readU32();
    args->pCreateInfo_subresourceRange_baseArrayLayer = r->readU32();
    args->pCreateInfo_subresourceRange_layerCount = r->readU32();
}

struct VnDecode_vkCreateSampler {
    uint64_t device;
    uint64_t pSampler;
    uint32_t pCreateInfo_flags;
    uint32_t pCreateInfo_magFilter;
    uint32_t pCreateInfo_minFilter;
    uint32_t pCreateInfo_mipmapMode;
    uint32_t pCreateInfo_addressModeU;
    uint32_t pCreateInfo_addressModeV;
    uint32_t pCreateInfo_addressModeW;
    float pCreateInfo_mipLodBias;
    uint32_t pCreateInfo_anisotropyEnable;
    float pCreateInfo_maxAnisotropy;
    uint32_t pCreateInfo_compareEnable;
    uint32_t pCreateInfo_compareOp;
    float pCreateInfo_minLod;
    float pCreateInfo_maxLod;
    uint32_t pCreateInfo_borderColor;
    uint32_t pCreateInfo_unnormalizedCoordinates;
};

static inline void vn_decode_vkCreateSampler(VnStreamReader* r, VnDecode_vkCreateSampler* args)
{
    args->device = r->readU64();
    args->pSampler = r->readU64();
    args->pCreateInfo_flags = r->readU32();
    args->pCreateInfo_magFilter = r->readU32();
    args->pCreateInfo_minFilter = r->readU32();
    args->pCreateInfo_mipmapMode = r->readU32();
    args->pCreateInfo_addressModeU = r->readU32();
    args->pCreateInfo_addressModeV = r->readU32();
    args->pCreateInfo_addressModeW = r->readU32();
    args->pCreateInfo_mipLodBias = r->readF32();
    args->pCreateInfo_anisotropyEnable = r->readU32();
    args->pCreateInfo_maxAnisotropy = r->readF32();
    args->pCreateInfo_compareEnable = r->readU32();
    args->pCreateInfo_compareOp = r->readU32();
    args->pCreateInfo_minLod = r->readF32();
    args->pCreateInfo_maxLod = r->readF32();
    args->pCreateInfo_borderColor = r->readU32();
    args->pCreateInfo_unnormalizedCoordinates = r->readU32();
}

struct VnDecode_vkCreateSemaphore {
    uint64_t device;
    uint64_t pSemaphore;
    uint32_t pCreateInfo_flags;
};

static inline void vn_decode_vkCreateSemaphore(VnStreamReader* r, VnDecode_vkCreateSemaphore* args)
{
    args->device = r->readU64();
    args->pSemaphore = r->readU64();
    args->pCreateInfo_flags = r->readU32();
}

struct VnDecode_vkDestroyBuffer {
    uint64_t device;
    uint64_t buffer;
};

static inline void vn_decode_vkDestroyBuffer(VnStreamReader* r, VnDecode_vkDestroyBuffer* args)
{
    args->device = r->readU64();
    args->buffer = r->readU64();
}

struct VnDecode_vkDestroyCommandPool {
    uint64_t device;
    uint64_t commandPool;
};

static inline void vn_decode_vkDestroyCommandPool(VnStreamReader* r, VnDecode_vkDestroyCommandPool* args)
{
    args->device = r->readU64();
    args->commandPool = r->readU64();
}

struct VnDecode_vkDestroyDescriptorPool {
    uint64_t device;
    uint64_t descriptorPool;
};

static inline void vn_decode_vkDestroyDescriptorPool(VnStreamReader* r, VnDecode_vkDestroyDescriptorPool* args)
{
    args->device = r->readU64();
    args->descriptorPool = r->readU64();
}

struct VnDecode_vkDestroyDescriptorSetLayout {
    uint64_t device;
    uint64_t descriptorSetLayout;
};

static inline void vn_decode_vkDestroyDescriptorSetLayout(VnStreamReader* r, VnDecode_vkDestroyDescriptorSetLayout* args)
{
    args->device = r->readU64();
    args->descriptorSetLayout = r->readU64();
}

struct VnDecode_vkDestroyFence {
    uint64_t device;
    uint64_t fence;
};

static inline void vn_decode_vkDestroyFence(VnStreamReader* r, VnDecode_vkDestroyFence* args)
{
    args->device = r->readU64();
    args->fence = r->readU64();
}

struct VnDecode_vkDestroyFramebuffer {
    uint64_t device;
    uint64_t framebuffer;
};

static inline void vn_decode_vkDestroyFramebuffer(VnStreamReader* r, VnDecode_vkDestroyFramebuffer* args)
{
    args->device = r->readU64();
    args->framebuffer = r->readU64();
}

struct VnDecode_vkDestroyImage {
    uint64_t device;
    uint64_t image;
};

static inline void vn_decode_vkDestroyImage(VnStreamReader* r, VnDecode_vkDestroyImage* args)
{
    args->device = r->readU64();
    args->image = r->readU64();
}

struct VnDecode_vkDestroyImageView {
    uint64_t device;
    uint64_t imageView;
};

static inline void vn_decode_vkDestroyImageView(VnStreamReader* r, VnDecode_vkDestroyImageView* args)
{
    args->device = r->readU64();
    args->imageView = r->readU64();
}

struct VnDecode_vkDestroyPipeline {
    uint64_t device;
    uint64_t pipeline;
};

static inline void vn_decode_vkDestroyPipeline(VnStreamReader* r, VnDecode_vkDestroyPipeline* args)
{
    args->device = r->readU64();
    args->pipeline = r->readU64();
}

struct VnDecode_vkDestroyPipelineLayout {
    uint64_t device;
    uint64_t pipelineLayout;
};

static inline void vn_decode_vkDestroyPipelineLayout(VnStreamReader* r, VnDecode_vkDestroyPipelineLayout* args)
{
    args->device = r->readU64();
    args->pipelineLayout = r->readU64();
}

struct VnDecode_vkDestroyRenderPass {
    uint64_t device;
    uint64_t renderPass;
};

static inline void vn_decode_vkDestroyRenderPass(VnStreamReader* r, VnDecode_vkDestroyRenderPass* args)
{
    args->device = r->readU64();
    args->renderPass = r->readU64();
}

struct VnDecode_vkDestroySampler {
    uint64_t device;
    uint64_t sampler;
};

static inline void vn_decode_vkDestroySampler(VnStreamReader* r, VnDecode_vkDestroySampler* args)
{
    args->device = r->readU64();
    args->sampler = r->readU64();
}

struct VnDecode_vkDestroySemaphore {
    uint64_t device;
    uint64_t semaphore;
};

static inline void vn_decode_vkDestroySemaphore(VnStreamReader* r, VnDecode_vkDestroySemaphore* args)
{
    args->device = r->readU64();
    args->semaphore = r->readU64();
}

struct VnDecode_vkDestroyShaderModule {
    uint64_t device;
    uint64_t shaderModule;
};

static inline void vn_decode_vkDestroyShaderModule(VnStreamReader* r, VnDecode_vkDestroyShaderModule* args)
{
    args->device = r->readU64();
    args->shaderModule = r->readU64();
}

struct VnDecode_vkEndCommandBuffer {
    uint64_t commandBuffer;
};

static inline void vn_decode_vkEndCommandBuffer(VnStreamReader* r, VnDecode_vkEndCommandBuffer* args)
{
    args->commandBuffer = r->readU64();
}

struct VnDecode_vkFreeMemory {
    uint64_t device;
    uint64_t memory;
};

static inline void vn_decode_vkFreeMemory(VnStreamReader* r, VnDecode_vkFreeMemory* args)
{
    args->device = r->readU64();
    args->memory = r->readU64();
}

struct VnDecode_vkResetFences {
    uint64_t device;
    uint32_t fenceCount;
    std::vector<uint64_t> pFences;
};

static inline void vn_decode_vkResetFences(VnStreamReader* r, VnDecode_vkResetFences* args)
{
    args->device = r->readU64();
    args->fenceCount = r->readU32();
    args->pFences.resize(args->fenceCount);
    for (uint32_t i = 0; i < args->fenceCount; i++)
        args->pFences[i] = r->readU64();
}

struct VnDecode_vkWaitForFences {
    uint64_t device;
    uint32_t fenceCount;
    std::vector<uint64_t> pFences;
    uint32_t waitAll;
    uint64_t timeout;
};

static inline void vn_decode_vkWaitForFences(VnStreamReader* r, VnDecode_vkWaitForFences* args)
{
    args->device = r->readU64();
    args->fenceCount = r->readU32();
    args->pFences.resize(args->fenceCount);
    for (uint32_t i = 0; i < args->fenceCount; i++)
        args->pFences[i] = r->readU64();
    args->waitAll = r->readU32();
    args->timeout = r->readU64();
}
